// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package store

import (
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

type Membership struct {
	OrgID     string
	UserID    string
	Role      string
	CreatedAt pgtype.Timestamptz
}

type Org struct {
	ID        string
	Slug      string
	Name      string
	CreatedAt pgtype.Timestamptz
}

type OrgKind struct {
	OrgID     string
	Kind      string
	CreatedAt pgtype.Timestamptz
}

type Session struct {
	ID         string
	UserID     string
	TokenHash  string
	UserAgent  *string
	Ip         *netip.Addr
	LastSeenAt pgtype.Timestamptz
	ExpiresAt  pgtype.Timestamptz
	DeletedAt  pgtype.Timestamptz
	CreatedAt  pgtype.Timestamptz
}

type User struct {
	ID           string
	Email        string
	Name         string
	PasswordHash string
	AvatarURL    *string
	DeletedAt    pgtype.Timestamptz
	CreatedAt    pgtype.Timestamptz
	IsShadow     bool
}
