// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

type Agent struct {
	ID                string
	OrgID             string
	ProjectID         string
	Name              string
	Provider          string
	Model             string
	ReasoningEffort   string
	SkillsJson        []byte
	ToolsJson         []byte
	MaxRuntimeSeconds int32
	RetryPolicy       string
	MaxAttempts       int32
	ProviderApiKeyEnc []byte
	CreatedAt         pgtype.Timestamptz
}

type AuditLog struct {
	ID           int64
	OrgID        string
	ActorUserID  *string
	ActorAgentID *string
	Action       string
	TargetType   string
	TargetID     string
	BeforeJson   []byte
	AfterJson    []byte
	Ip           string
	CreatedAt    pgtype.Timestamptz
}

type Board struct {
	ID                string
	OrgID             string
	ProjectID         string
	Slug              string
	Name              string
	ColumnsJson       []byte
	BudgetDailyMicros int64
	CreatedAt         pgtype.Timestamptz
}

type Event struct {
	ID          int64
	OrgID       string
	BoardID     *string
	TaskID      *string
	RunID       *string
	Kind        string
	PayloadJson []byte
	CreatedAt   pgtype.Timestamptz
}

type Membership struct {
	OrgID     string
	UserID    string
	Role      string
	CreatedAt pgtype.Timestamptz
}

type Org struct {
	ID        string
	Slug      string
	Name      string
	CreatedAt pgtype.Timestamptz
}

type OrgKind struct {
	OrgID     string
	Kind      string
	CreatedAt pgtype.Timestamptz
}

type PasswordReset struct {
	TokenHash string
	UserID    string
	ExpiresAt pgtype.Timestamptz
	UsedAt    pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
}

type Project struct {
	ID        string
	OrgID     string
	Slug      string
	Name      string
	CreatedAt pgtype.Timestamptz
}

type Session struct {
	ID         string
	UserID     string
	TokenHash  string
	UserAgent  *string
	Ip         *netip.Addr
	LastSeenAt pgtype.Timestamptz
	ExpiresAt  pgtype.Timestamptz
	DeletedAt  pgtype.Timestamptz
	CreatedAt  pgtype.Timestamptz
}

type Task struct {
	ID                  string
	OrgID               string
	BoardID             string
	Title               string
	Body                string
	Status              string
	Priority            int16
	AssigneeAgentID     *string
	CreatedBy           string
	IdempotencyKey      *string
	BlockKind           *string
	ConsecutiveFailures int16
	WorkspaceKind       string
	WorkspacePath       *string
	BranchName          *string
	CompletionContract  *string
	GoalMode            string
	GoalMaxTurns        int32
	CurrentRunID        *string
	CostMicros          int64
	TokensIn            int64
	TokensOut           int64
	CreatedAt           pgtype.Timestamptz
	StartedAt           pgtype.Timestamptz
	CompletedAt         pgtype.Timestamptz
	ArchivedAt          pgtype.Timestamptz
}

type TaskLink struct {
	ParentID string
	ChildID  string
}

type User struct {
	ID           string
	Email        string
	Name         string
	PasswordHash string
	AvatarURL    *string
	DeletedAt    pgtype.Timestamptz
	CreatedAt    pgtype.Timestamptz
	IsShadow     bool
}
