// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

type Agent struct {
	ID                string
	OrgID             string
	ProjectID         string
	Name              string
	Provider          string
	Model             string
	ReasoningEffort   string
	SkillsJson        []byte
	ToolsJson         []byte
	MaxRuntimeSeconds int32
	RetryPolicy       string
	MaxAttempts       int32
	ProviderApiKeyEnc []byte
	CreatedAt         pgtype.Timestamptz
	ArchivedAt        pgtype.Timestamptz
	HasProviderKey    *bool
	ProviderID        *string
}

type AgentModelPrice struct {
	ID                    string
	OrgID                 string
	Model                 string
	InputMicrosPer1m      int64
	OutputMicrosPer1m     int64
	CachedMicrosPer1m     int64
	ReasoningMicrosPer1m  int64
	CacheWriteMicrosPer1m int64
	CreatedBy             *string
	CreatedAt             pgtype.Timestamptz
	UpdatedAt             pgtype.Timestamptz
}

type AgentSkill struct {
	ID        string
	OrgID     string
	Slug      string
	Name      string
	BodyMd    string
	Version   int32
	IsSystem  bool
	CreatedBy *string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type Approval struct {
	ID          string
	OrgID       string
	TaskID      string
	RunID       string
	RequestedBy string
	DecidedBy   *string
	Decision    string
	GateMode    string
	Reason      *string
	PreviewJson []byte
	ExpiresAt   pgtype.Timestamptz
	DecidedAt   pgtype.Timestamptz
	CreatedAt   pgtype.Timestamptz
}

type Artifact struct {
	ID          string
	OrgID       string
	TaskID      string
	RunID       string
	Filename    string
	ContentType string
	Size        int32
	StorageKey  string
	Sha256      string
	CreatedAt   pgtype.Timestamptz
}

type AuditLog struct {
	ID           int64
	OrgID        string
	ActorUserID  *string
	ActorAgentID *string
	Action       string
	TargetType   string
	TargetID     string
	BeforeJson   []byte
	AfterJson    []byte
	Ip           string
	CreatedAt    pgtype.Timestamptz
}

type Board struct {
	ID                string
	OrgID             string
	ProjectID         string
	Slug              string
	Name              string
	ColumnsJson       []byte
	BudgetDailyMicros int64
	CreatedAt         pgtype.Timestamptz
}

type DailyBoardCost struct {
	OrgID       string
	BoardID     string
	Day         pgtype.Date
	TotalMicros int64
	RunCount    int32
	TokensIn    int64
	TokensOut   int64
	UpdatedAt   pgtype.Timestamptz
}

type Event struct {
	ID          int64
	OrgID       string
	BoardID     *string
	TaskID      *string
	RunID       *string
	Kind        string
	PayloadJson []byte
	CreatedAt   pgtype.Timestamptz
}

type LedgerEntry struct {
	ID               int64
	OrgID            string
	RunID            string
	TaskID           string
	Provider         string
	Model            string
	Kind             string
	TokensIn         int64
	TokensOut        int64
	CacheReadTokens  int64
	CacheWriteTokens int64
	ReasoningTokens  int64
	CostMicros       int64
	PriceVersion     int32
	PriceSource      string
	PricingModel     string
	CreatedAt        pgtype.Timestamptz
}

type Membership struct {
	OrgID     string
	UserID    string
	Role      string
	CreatedAt pgtype.Timestamptz
}

type Org struct {
	ID        string
	Slug      string
	Name      string
	CreatedAt pgtype.Timestamptz
}

type OrgKind struct {
	OrgID     string
	Kind      string
	CreatedAt pgtype.Timestamptz
}

type PasswordReset struct {
	TokenHash string
	UserID    string
	ExpiresAt pgtype.Timestamptz
	UsedAt    pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
}

type Project struct {
	ID        string
	OrgID     string
	Slug      string
	Name      string
	CreatedAt pgtype.Timestamptz
}

type Provider struct {
	ID              string
	OrgID           string
	Name            string
	Protocol        string
	BaseUrl         string
	ApiKeyEnc       []byte
	ModelsJson      []byte
	ModelsFetchedAt pgtype.Timestamptz
	LastVerifiedAt  pgtype.Timestamptz
	IsDefault       bool
	CreatedAt       pgtype.Timestamptz
}

type Run struct {
	ID                string
	OrgID             string
	TaskID            string
	AgentID           string
	Attempt           int16
	Status            string
	Outcome           *string
	FailureKind       *string
	ClaimLock         *string
	ClaimExpires      pgtype.Timestamptz
	WorkerPid         *int32
	LastHeartbeatAt   pgtype.Timestamptz
	MaxRuntimeSeconds int32
	CostMicros        int64
	TokensIn          int64
	TokensOut         int64
	Summary           *string
	Error             *string
	MetadataJson      []byte
	StartedAt         pgtype.Timestamptz
	EndedAt           pgtype.Timestamptz
	CancelRequestedAt pgtype.Timestamptz
}

type Session struct {
	ID         string
	UserID     string
	TokenHash  string
	UserAgent  *string
	Ip         *netip.Addr
	LastSeenAt pgtype.Timestamptz
	ExpiresAt  pgtype.Timestamptz
	DeletedAt  pgtype.Timestamptz
	CreatedAt  pgtype.Timestamptz
}

type Step struct {
	ID          int64
	OrgID       string
	RunID       string
	Seq         int16
	Kind        string
	Name        string
	Status      string
	TokensIn    int64
	TokensOut   int64
	CostMicros  int64
	StartedAt   pgtype.Timestamptz
	EndedAt     pgtype.Timestamptz
	PayloadJson []byte
}

type Task struct {
	ID                  string
	OrgID               string
	BoardID             string
	Title               string
	Body                string
	Status              string
	Priority            int16
	AssigneeAgentID     *string
	CreatedBy           string
	IdempotencyKey      *string
	BlockKind           *string
	ConsecutiveFailures int16
	WorkspaceKind       string
	WorkspacePath       *string
	BranchName          *string
	CompletionContract  *string
	GoalMode            string
	GoalMaxTurns        int32
	CurrentRunID        *string
	CostMicros          int64
	TokensIn            int64
	TokensOut           int64
	CreatedAt           pgtype.Timestamptz
	StartedAt           pgtype.Timestamptz
	CompletedAt         pgtype.Timestamptz
	ArchivedAt          pgtype.Timestamptz
}

type TaskLink struct {
	ParentID string
	ChildID  string
}

type User struct {
	ID           string
	Email        string
	Name         string
	PasswordHash string
	AvatarURL    *string
	DeletedAt    pgtype.Timestamptz
	CreatedAt    pgtype.Timestamptz
	IsShadow     bool
}
