// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: password_reset.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const consumePasswordReset = `-- name: ConsumePasswordReset :execrows
UPDATE password_resets
SET used_at = now()
WHERE token_hash = $1
  AND used_at IS NULL
  AND expires_at > now()
`

func (q *Queries) ConsumePasswordReset(ctx context.Context, tokenHash string) (int64, error) {
	result, err := q.db.Exec(ctx, consumePasswordReset, tokenHash)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const createPasswordReset = `-- name: CreatePasswordReset :exec

INSERT INTO password_resets (token_hash, user_id, expires_at, created_at)
VALUES ($1, $2, $3, $4)
`

type CreatePasswordResetParams struct {
	TokenHash string
	UserID    string
	ExpiresAt pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
}

// M0 — password reset (US-AD88).
//
// The token is single-use and time-boxed, so the row is consumed by an UPDATE
// that also stamps used_at: a SELECT-then-UPDATE pair would let two concurrent
// redemptions both read an unconsumed row. Expiry and single-use are both in
// the WHERE clause, so an expired or already-spent token matches zero rows and
// the caller cannot tell the two apart (AC3).
func (q *Queries) CreatePasswordReset(ctx context.Context, arg CreatePasswordResetParams) error {
	_, err := q.db.Exec(ctx, createPasswordReset,
		arg.TokenHash,
		arg.UserID,
		arg.ExpiresAt,
		arg.CreatedAt,
	)
	return err
}

const deleteUserSessions = `-- name: DeleteUserSessions :exec
UPDATE sessions
SET deleted_at = now()
WHERE user_id = $1 AND deleted_at IS NULL
`

// Revokes every session of one user (US-AD88 AC2). Deliberately not scoped by
// token: after a reset the operator has no trusted device, so all of them go.
func (q *Queries) DeleteUserSessions(ctx context.Context, userID string) error {
	_, err := q.db.Exec(ctx, deleteUserSessions, userID)
	return err
}

const getPasswordReset = `-- name: GetPasswordReset :one
SELECT token_hash, user_id, expires_at, used_at, created_at
FROM password_resets
WHERE token_hash = $1
`

func (q *Queries) GetPasswordReset(ctx context.Context, tokenHash string) (PasswordReset, error) {
	row := q.db.QueryRow(ctx, getPasswordReset, tokenHash)
	var i PasswordReset
	err := row.Scan(
		&i.TokenHash,
		&i.UserID,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const updateUserPassword = `-- name: UpdateUserPassword :exec
UPDATE users
SET password_hash = $2
WHERE id = $1 AND deleted_at IS NULL
`

type UpdateUserPasswordParams struct {
	ID           string
	PasswordHash string
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error {
	_, err := q.db.Exec(ctx, updateUserPassword, arg.ID, arg.PasswordHash)
	return err
}
