// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: queries.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimShadowUser = `-- name: ClaimShadowUser :exec
UPDATE users
SET name          = $2,
    password_hash = $3,
    is_shadow     = false
WHERE lower(email) = lower($1) AND is_shadow
`

type ClaimShadowUserParams struct {
	Lower        string
	Name         string
	PasswordHash string
}

func (q *Queries) ClaimShadowUser(ctx context.Context, arg ClaimShadowUserParams) error {
	_, err := q.db.Exec(ctx, claimShadowUser, arg.Lower, arg.Name, arg.PasswordHash)
	return err
}

const countOrgOwners = `-- name: CountOrgOwners :one
SELECT count(*)::int
FROM memberships
WHERE org_id = $1 AND role = 'owner'
`

// Guards the last-owner rule: an org must never be left without an owner.
func (q *Queries) CountOrgOwners(ctx context.Context, orgID string) (int32, error) {
	row := q.db.QueryRow(ctx, countOrgOwners, orgID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const createMembership = `-- name: CreateMembership :exec
INSERT INTO memberships (org_id, user_id, role)
VALUES ($1, $2, $3)
ON CONFLICT (org_id, user_id) DO UPDATE
SET role = EXCLUDED.role
`

type CreateMembershipParams struct {
	OrgID  string
	UserID string
	Role   string
}

func (q *Queries) CreateMembership(ctx context.Context, arg CreateMembershipParams) error {
	_, err := q.db.Exec(ctx, createMembership, arg.OrgID, arg.UserID, arg.Role)
	return err
}

const createOrg = `-- name: CreateOrg :one
INSERT INTO orgs (id, slug, name)
VALUES ($1, $2, $3)
RETURNING id, slug, name, created_at
`

type CreateOrgParams struct {
	ID   string
	Slug string
	Name string
}

func (q *Queries) CreateOrg(ctx context.Context, arg CreateOrgParams) (Org, error) {
	row := q.db.QueryRow(ctx, createOrg, arg.ID, arg.Slug, arg.Name)
	var i Org
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}

const createOrgKind = `-- name: CreateOrgKind :exec
INSERT INTO org_kinds (org_id, kind)
VALUES ($1, $2)
`

type CreateOrgKindParams struct {
	OrgID string
	Kind  string
}

func (q *Queries) CreateOrgKind(ctx context.Context, arg CreateOrgKindParams) error {
	_, err := q.db.Exec(ctx, createOrgKind, arg.OrgID, arg.Kind)
	return err
}

const createSession = `-- name: CreateSession :exec
INSERT INTO sessions (id, user_id, token_hash, expires_at, last_seen_at, created_at)
VALUES ($1, $2, $3, $4, $5, $6)
`

type CreateSessionParams struct {
	ID         string
	UserID     string
	TokenHash  string
	ExpiresAt  pgtype.Timestamptz
	LastSeenAt pgtype.Timestamptz
	CreatedAt  pgtype.Timestamptz
}

// token_hash is SHA-256 of the 64-byte raw token; the raw token only ever
// exists in the Set-Cookie (ARCHITECTURE 3.19).
func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) error {
	_, err := q.db.Exec(ctx, createSession,
		arg.ID,
		arg.UserID,
		arg.TokenHash,
		arg.ExpiresAt,
		arg.LastSeenAt,
		arg.CreatedAt,
	)
	return err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (id, email, name, password_hash, is_shadow)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, email, name, password_hash, avatar_url, is_shadow, deleted_at, created_at
`

type CreateUserParams struct {
	ID           string
	Email        string
	Name         string
	PasswordHash string
	IsShadow     bool
}

type CreateUserRow struct {
	ID           string
	Email        string
	Name         string
	PasswordHash string
	AvatarURL    *string
	IsShadow     bool
	DeletedAt    pgtype.Timestamptz
	CreatedAt    pgtype.Timestamptz
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.ID,
		arg.Email,
		arg.Name,
		arg.PasswordHash,
		arg.IsShadow,
	)
	var i CreateUserRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.PasswordHash,
		&i.AvatarURL,
		&i.IsShadow,
		&i.DeletedAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :exec
DELETE FROM sessions
WHERE expires_at < now()
`

func (q *Queries) DeleteExpiredSessions(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredSessions)
	return err
}

const deleteMembership = `-- name: DeleteMembership :exec
DELETE FROM memberships
WHERE org_id = $1 AND user_id = $2
`

type DeleteMembershipParams struct {
	OrgID  string
	UserID string
}

func (q *Queries) DeleteMembership(ctx context.Context, arg DeleteMembershipParams) error {
	_, err := q.db.Exec(ctx, deleteMembership, arg.OrgID, arg.UserID)
	return err
}

const deleteSessionByTokenHash = `-- name: DeleteSessionByTokenHash :exec
UPDATE sessions
SET deleted_at = now()
WHERE token_hash = $1 AND deleted_at IS NULL
`

func (q *Queries) DeleteSessionByTokenHash(ctx context.Context, tokenHash string) error {
	_, err := q.db.Exec(ctx, deleteSessionByTokenHash, tokenHash)
	return err
}

const getMembership = `-- name: GetMembership :one
SELECT org_id, user_id, role, created_at
FROM memberships
WHERE org_id = $1 AND user_id = $2
`

type GetMembershipParams struct {
	OrgID  string
	UserID string
}

// The single membership row that answers "is this user in this org, and as
// what". Every org-scoped handler resolves its tenant through this query, so
// there is no second code path that could forget the org_id scope.
func (q *Queries) GetMembership(ctx context.Context, arg GetMembershipParams) (Membership, error) {
	row := q.db.QueryRow(ctx, getMembership, arg.OrgID, arg.UserID)
	var i Membership
	err := row.Scan(
		&i.OrgID,
		&i.UserID,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}

const getOrgByID = `-- name: GetOrgByID :one
SELECT id, slug, name, created_at
FROM orgs
WHERE id = $1
`

func (q *Queries) GetOrgByID(ctx context.Context, id string) (Org, error) {
	row := q.db.QueryRow(ctx, getOrgByID, id)
	var i Org
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}

const getPersonalWorkspace = `-- name: GetPersonalWorkspace :one
SELECT o.id, o.slug, o.name, o.created_at
FROM org_kinds k
JOIN orgs o ON o.id = k.org_id
WHERE k.kind = 'registration'
  AND EXISTS (
      SELECT 1 FROM memberships m
      WHERE m.org_id = o.id AND m.user_id = $1
  )
`

func (q *Queries) GetPersonalWorkspace(ctx context.Context, userID string) (Org, error) {
	row := q.db.QueryRow(ctx, getPersonalWorkspace, userID)
	var i Org
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}

const getSessionByTokenHash = `-- name: GetSessionByTokenHash :one
SELECT id, user_id, token_hash, last_seen_at, expires_at, created_at
FROM sessions
WHERE token_hash = $1
  AND deleted_at IS NULL
  AND expires_at > now()
  AND last_seen_at > now() - ($2::interval)
`

type GetSessionByTokenHashParams struct {
	TokenHash string
	Column2   pgtype.Interval
}

type GetSessionByTokenHashRow struct {
	ID         string
	UserID     string
	TokenHash  string
	LastSeenAt pgtype.Timestamptz
	ExpiresAt  pgtype.Timestamptz
	CreatedAt  pgtype.Timestamptz
}

// Sliding idle window (US-AD02 AC4): a session that has been idle longer than
// the idle timeout is rejected, so last_seen_at is bumped on every use.
func (q *Queries) GetSessionByTokenHash(ctx context.Context, arg GetSessionByTokenHashParams) (GetSessionByTokenHashRow, error) {
	row := q.db.QueryRow(ctx, getSessionByTokenHash, arg.TokenHash, arg.Column2)
	var i GetSessionByTokenHashRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.LastSeenAt,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, name, password_hash, avatar_url, is_shadow, deleted_at, created_at
FROM users
WHERE lower(email) = lower($1) AND deleted_at IS NULL
`

type GetUserByEmailRow struct {
	ID           string
	Email        string
	Name         string
	PasswordHash string
	AvatarURL    *string
	IsShadow     bool
	DeletedAt    pgtype.Timestamptz
	CreatedAt    pgtype.Timestamptz
}

func (q *Queries) GetUserByEmail(ctx context.Context, lower string) (GetUserByEmailRow, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, lower)
	var i GetUserByEmailRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.PasswordHash,
		&i.AvatarURL,
		&i.IsShadow,
		&i.DeletedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, name, password_hash, avatar_url, is_shadow, deleted_at, created_at
FROM users
WHERE id = $1 AND deleted_at IS NULL
`

type GetUserByIDRow struct {
	ID           string
	Email        string
	Name         string
	PasswordHash string
	AvatarURL    *string
	IsShadow     bool
	DeletedAt    pgtype.Timestamptz
	CreatedAt    pgtype.Timestamptz
}

func (q *Queries) GetUserByID(ctx context.Context, id string) (GetUserByIDRow, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i GetUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.PasswordHash,
		&i.AvatarURL,
		&i.IsShadow,
		&i.DeletedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listMembers = `-- name: ListMembers :many
SELECT m.user_id, u.email, u.name, m.role, m.created_at
FROM memberships m
JOIN users u ON u.id = m.user_id
WHERE m.org_id = $1
ORDER BY m.created_at, u.email
`

type ListMembersRow struct {
	UserID    string
	Email     string
	Name      string
	Role      string
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) ListMembers(ctx context.Context, orgID string) ([]ListMembersRow, error) {
	rows, err := q.db.Query(ctx, listMembers, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMembersRow
	for rows.Next() {
		var i ListMembersRow
		if err := rows.Scan(
			&i.UserID,
			&i.Email,
			&i.Name,
			&i.Role,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrgsForUser = `-- name: ListOrgsForUser :many
SELECT m.org_id, o.slug, o.name, k.kind, m.role
FROM memberships m
JOIN orgs o ON o.id = m.org_id
LEFT JOIN org_kinds k ON k.org_id = m.org_id
WHERE m.user_id = $1
ORDER BY m.created_at
`

type ListOrgsForUserRow struct {
	OrgID string
	Slug  string
	Name  string
	Kind  *string
	Role  string
}

// The org roster a user belongs to, with their role in each. Scoping is
// by membership, not by the caller's guess of an org id, so this cannot
// leak a tenant the user is not part of (tenant isolation, ARCHITECTURE 17).
func (q *Queries) ListOrgsForUser(ctx context.Context, userID string) ([]ListOrgsForUserRow, error) {
	rows, err := q.db.Query(ctx, listOrgsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOrgsForUserRow
	for rows.Next() {
		var i ListOrgsForUserRow
		if err := rows.Scan(
			&i.OrgID,
			&i.Slug,
			&i.Name,
			&i.Kind,
			&i.Role,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const touchSession = `-- name: TouchSession :exec
UPDATE sessions
SET last_seen_at = now()
WHERE token_hash = $1 AND deleted_at IS NULL
`

func (q *Queries) TouchSession(ctx context.Context, tokenHash string) error {
	_, err := q.db.Exec(ctx, touchSession, tokenHash)
	return err
}

const updateMembershipRole = `-- name: UpdateMembershipRole :exec
UPDATE memberships
SET role = $3
WHERE org_id = $1 AND user_id = $2
`

type UpdateMembershipRoleParams struct {
	OrgID  string
	UserID string
	Role   string
}

func (q *Queries) UpdateMembershipRole(ctx context.Context, arg UpdateMembershipRoleParams) error {
	_, err := q.db.Exec(ctx, updateMembershipRole, arg.OrgID, arg.UserID, arg.Role)
	return err
}

const updateOrgName = `-- name: UpdateOrgName :exec
UPDATE orgs
SET name = $2
WHERE id = $1
`

type UpdateOrgNameParams struct {
	ID   string
	Name string
}

func (q *Queries) UpdateOrgName(ctx context.Context, arg UpdateOrgNameParams) error {
	_, err := q.db.Exec(ctx, updateOrgName, arg.ID, arg.Name)
	return err
}
