// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package store

import (
	"context"
)

type Querier interface {
	ClaimShadowUser(ctx context.Context, arg ClaimShadowUserParams) error
	// Guards the last-owner rule: an org must never be left without an owner.
	CountOrgOwners(ctx context.Context, orgID string) (int32, error)
	CreateMembership(ctx context.Context, arg CreateMembershipParams) error
	CreateOrg(ctx context.Context, arg CreateOrgParams) (Org, error)
	CreateOrgKind(ctx context.Context, arg CreateOrgKindParams) error
	// token_hash is SHA-256 of the 64-byte raw token; the raw token only ever
	// exists in the Set-Cookie (ARCHITECTURE 3.19).
	CreateSession(ctx context.Context, arg CreateSessionParams) error
	CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error)
	DeleteExpiredSessions(ctx context.Context) error
	DeleteMembership(ctx context.Context, arg DeleteMembershipParams) error
	DeleteSessionByTokenHash(ctx context.Context, tokenHash string) error
	// The single membership row that answers "is this user in this org, and as
	// what". Every org-scoped handler resolves its tenant through this query, so
	// there is no second code path that could forget the org_id scope.
	GetMembership(ctx context.Context, arg GetMembershipParams) (Membership, error)
	GetOrgByID(ctx context.Context, id string) (Org, error)
	GetPersonalWorkspace(ctx context.Context, userID string) (Org, error)
	// Sliding idle window (US-AD02 AC4): a session that has been idle longer than
	// the idle timeout is rejected, so last_seen_at is bumped on every use.
	GetSessionByTokenHash(ctx context.Context, arg GetSessionByTokenHashParams) (GetSessionByTokenHashRow, error)
	GetUserByEmail(ctx context.Context, lower string) (GetUserByEmailRow, error)
	GetUserByID(ctx context.Context, id string) (GetUserByIDRow, error)
	ListMembers(ctx context.Context, orgID string) ([]ListMembersRow, error)
	// The org roster a user belongs to, with their role in each. Scoping is
	// by membership, not by the caller's guess of an org id, so this cannot
	// leak a tenant the user is not part of (tenant isolation, ARCHITECTURE 17).
	ListOrgsForUser(ctx context.Context, userID string) ([]ListOrgsForUserRow, error)
	TouchSession(ctx context.Context, tokenHash string) error
	UpdateMembershipRole(ctx context.Context, arg UpdateMembershipRoleParams) error
	UpdateOrgName(ctx context.Context, arg UpdateOrgNameParams) error
}

var _ Querier = (*Queries)(nil)
