// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const archiveAgent = `-- name: ArchiveAgent :one
UPDATE agents
SET archived_at = now()
WHERE id = $1 AND org_id = $2
RETURNING id, org_id, project_id, name, provider, model, reasoning_effort, skills_json,
          tools_json, max_runtime_seconds, retry_policy, max_attempts,
          archived_at, created_at, has_provider_key, provider_id
`

type ArchiveAgentParams struct {
	ID    string
	OrgID string
}

type ArchiveAgentRow struct {
	ID                string
	OrgID             string
	ProjectID         string
	Name              string
	Provider          string
	Model             string
	ReasoningEffort   string
	SkillsJson        []byte
	ToolsJson         []byte
	MaxRuntimeSeconds int32
	RetryPolicy       string
	MaxAttempts       int32
	ArchivedAt        pgtype.Timestamptz
	CreatedAt         pgtype.Timestamptz
	HasProviderKey    *bool
	ProviderID        *string
}

// US-AD73: archived agents keep their row (running tasks still resolve their
// retry/limit source) but disappear from every assign dropdown.
func (q *Queries) ArchiveAgent(ctx context.Context, arg ArchiveAgentParams) (ArchiveAgentRow, error) {
	row := q.db.QueryRow(ctx, archiveAgent, arg.ID, arg.OrgID)
	var i ArchiveAgentRow
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ProjectID,
		&i.Name,
		&i.Provider,
		&i.Model,
		&i.ReasoningEffort,
		&i.SkillsJson,
		&i.ToolsJson,
		&i.MaxRuntimeSeconds,
		&i.RetryPolicy,
		&i.MaxAttempts,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.HasProviderKey,
		&i.ProviderID,
	)
	return i, err
}

const assignTask = `-- name: AssignTask :one
UPDATE tasks
SET assignee_agent_id = $3
WHERE id = $1 AND org_id = $2
RETURNING id, org_id, board_id, title, body, status, priority, assignee_agent_id, created_by,
          idempotency_key, block_kind, consecutive_failures, workspace_kind, workspace_path,
          branch_name, completion_contract, goal_mode, goal_max_turns, current_run_id,
          cost_micros, tokens_in, tokens_out, created_at, started_at, completed_at, archived_at
`

type AssignTaskParams struct {
	ID              string
	OrgID           string
	AssigneeAgentID *string
}

func (q *Queries) AssignTask(ctx context.Context, arg AssignTaskParams) (Task, error) {
	row := q.db.QueryRow(ctx, assignTask, arg.ID, arg.OrgID, arg.AssigneeAgentID)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.BoardID,
		&i.Title,
		&i.Body,
		&i.Status,
		&i.Priority,
		&i.AssigneeAgentID,
		&i.CreatedBy,
		&i.IdempotencyKey,
		&i.BlockKind,
		&i.ConsecutiveFailures,
		&i.WorkspaceKind,
		&i.WorkspacePath,
		&i.BranchName,
		&i.CompletionContract,
		&i.GoalMode,
		&i.GoalMaxTurns,
		&i.CurrentRunID,
		&i.CostMicros,
		&i.TokensIn,
		&i.TokensOut,
		&i.CreatedAt,
		&i.StartedAt,
		&i.CompletedAt,
		&i.ArchivedAt,
	)
	return i, err
}

const claimReadyTasks = `-- name: ClaimReadyTasks :many
WITH claimed AS (
    SELECT t.id
    FROM tasks t
    WHERE t.org_id = $1 AND t.board_id = $2
      AND t.status = 'ready'
      AND t.current_run_id IS NULL
    ORDER BY t.priority DESC, t.created_at DESC
    LIMIT $3
    FOR UPDATE SKIP LOCKED
)
UPDATE tasks t
SET status = 'running',
    current_run_id = $4,
    started_at = COALESCE(t.started_at, now())
FROM claimed c
WHERE t.id = c.id
RETURNING t.id, t.org_id, t.board_id, t.title, t.body, t.status, t.priority,
          t.assignee_agent_id, t.created_by, t.idempotency_key, t.block_kind,
          t.consecutive_failures, t.workspace_kind, t.workspace_path, t.branch_name,
          t.completion_contract, t.goal_mode, t.goal_max_turns, t.current_run_id,
          t.cost_micros, t.tokens_in, t.tokens_out, t.created_at, t.started_at,
          t.completed_at, t.archived_at
`

type ClaimReadyTasksParams struct {
	OrgID        string
	BoardID      string
	Limit        int32
	CurrentRunID *string
}

func (q *Queries) ClaimReadyTasks(ctx context.Context, arg ClaimReadyTasksParams) ([]Task, error) {
	rows, err := q.db.Query(ctx, claimReadyTasks,
		arg.OrgID,
		arg.BoardID,
		arg.Limit,
		arg.CurrentRunID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.BoardID,
			&i.Title,
			&i.Body,
			&i.Status,
			&i.Priority,
			&i.AssigneeAgentID,
			&i.CreatedBy,
			&i.IdempotencyKey,
			&i.BlockKind,
			&i.ConsecutiveFailures,
			&i.WorkspaceKind,
			&i.WorkspacePath,
			&i.BranchName,
			&i.CompletionContract,
			&i.GoalMode,
			&i.GoalMaxTurns,
			&i.CurrentRunID,
			&i.CostMicros,
			&i.TokensIn,
			&i.TokensOut,
			&i.CreatedAt,
			&i.StartedAt,
			&i.CompletedAt,
			&i.ArchivedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const claimShadowUser = `-- name: ClaimShadowUser :exec
UPDATE users
SET name          = $2,
    password_hash = $3,
    is_shadow     = false
WHERE lower(email) = lower($1) AND is_shadow
`

type ClaimShadowUserParams struct {
	Lower        string
	Name         string
	PasswordHash string
}

func (q *Queries) ClaimShadowUser(ctx context.Context, arg ClaimShadowUserParams) error {
	_, err := q.db.Exec(ctx, claimShadowUser, arg.Lower, arg.Name, arg.PasswordHash)
	return err
}

const clearAgentProviderKey = `-- name: ClearAgentProviderKey :one
UPDATE agents
SET provider_api_key_enc = NULL
WHERE id = $1 AND org_id = $2
RETURNING id, has_provider_key
`

type ClearAgentProviderKeyParams struct {
	ID    string
	OrgID string
}

type ClearAgentProviderKeyRow struct {
	ID             string
	HasProviderKey *bool
}

// Rotation and revocation are the same statement with a NULL ciphertext.
func (q *Queries) ClearAgentProviderKey(ctx context.Context, arg ClearAgentProviderKeyParams) (ClearAgentProviderKeyRow, error) {
	row := q.db.QueryRow(ctx, clearAgentProviderKey, arg.ID, arg.OrgID)
	var i ClearAgentProviderKeyRow
	err := row.Scan(&i.ID, &i.HasProviderKey)
	return i, err
}

const clearDefaultProvider = `-- name: ClearDefaultProvider :exec
UPDATE providers SET is_default = false WHERE org_id = $1 AND is_default
`

// providers_org_default_key is a non-deferrable partial unique index, so a
// single `UPDATE ... SET is_default = (id = $x)` can still raise 23505: Postgres
// checks the index per row, and the new default may be visited before the old
// one is unset. Clearing first and setting second are two statements that
// cannot collide. AC9 makes the cleared state legitimate, not a half-write.
func (q *Queries) ClearDefaultProvider(ctx context.Context, orgID string) error {
	_, err := q.db.Exec(ctx, clearDefaultProvider, orgID)
	return err
}

const countAgentRunningTasks = `-- name: CountAgentRunningTasks :one
SELECT count(*) FROM tasks
WHERE assignee_agent_id = $1 AND org_id = $2 AND status = 'running'
`

type CountAgentRunningTasksParams struct {
	AssigneeAgentID *string
	OrgID           string
}

// Guards US-AD20 AC4: an agent holding a task in `running` may not be deleted,
// because the run it is executing would lose its retry/limit source mid-flight.
func (q *Queries) CountAgentRunningTasks(ctx context.Context, arg CountAgentRunningTasksParams) (int64, error) {
	row := q.db.QueryRow(ctx, countAgentRunningTasks, arg.AssigneeAgentID, arg.OrgID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countArchivedAgents = `-- name: CountArchivedAgents :one
SELECT count(*) FROM agents
WHERE org_id = $1 AND archived_at IS NOT NULL
`

// The assign picker hides archived agents (US-AD73 AC2). The count is what lets
// the board say "N hidden" instead of silently omitting rows — the design's own
// `✕ 1 agent diarsip disembunyikan` line.
func (q *Queries) CountArchivedAgents(ctx context.Context, orgID string) (int64, error) {
	row := q.db.QueryRow(ctx, countArchivedAgents, orgID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countBoardsInProject = `-- name: CountBoardsInProject :one
SELECT count(*)::int
FROM boards
WHERE org_id = $1 AND project_id = $2
`

type CountBoardsInProjectParams struct {
	OrgID     string
	ProjectID string
}

func (q *Queries) CountBoardsInProject(ctx context.Context, arg CountBoardsInProjectParams) (int32, error) {
	row := q.db.QueryRow(ctx, countBoardsInProject, arg.OrgID, arg.ProjectID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const countOrgOwners = `-- name: CountOrgOwners :one
SELECT count(*)::int
FROM memberships
WHERE org_id = $1 AND role = 'owner'
`

// Guards the last-owner rule: an org must never be left without an owner.
func (q *Queries) CountOrgOwners(ctx context.Context, orgID string) (int32, error) {
	row := q.db.QueryRow(ctx, countOrgOwners, orgID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const countProviders = `-- name: CountProviders :one
SELECT count(*)::int FROM providers WHERE org_id = $1
`

// Decides whether a provider being created becomes the workspace default: the
// first one does, so a workspace that has exactly one never has to pick.
func (q *Queries) CountProviders(ctx context.Context, orgID string) (int32, error) {
	row := q.db.QueryRow(ctx, countProviders, orgID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const countUnfinishedParents = `-- name: CountUnfinishedParents :one
SELECT count(*)::int
FROM task_links l
JOIN tasks t ON t.id = l.parent_id
WHERE l.child_id = $1 AND t.status NOT IN ('done', 'cancelled', 'archived')
`

// Counts unfinished parents: the dispatcher promotes a child to ready only when
// this returns zero (ARCHITECTURE 4e).
func (q *Queries) CountUnfinishedParents(ctx context.Context, childID string) (int32, error) {
	row := q.db.QueryRow(ctx, countUnfinishedParents, childID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const createAgent = `-- name: CreateAgent :one
INSERT INTO agents (id, org_id, project_id, name, provider, model, reasoning_effort,
                    skills_json, tools_json, max_runtime_seconds, retry_policy, max_attempts,
                    provider_id)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13)
RETURNING id, org_id, project_id, name, provider, model, reasoning_effort, skills_json,
          tools_json, max_runtime_seconds, retry_policy, max_attempts,
          archived_at, created_at, has_provider_key, provider_id
`

type CreateAgentParams struct {
	ID                string
	OrgID             string
	ProjectID         string
	Name              string
	Provider          string
	Model             string
	ReasoningEffort   string
	SkillsJson        []byte
	ToolsJson         []byte
	MaxRuntimeSeconds int32
	RetryPolicy       string
	MaxAttempts       int32
	ProviderID        *string
}

type CreateAgentRow struct {
	ID                string
	OrgID             string
	ProjectID         string
	Name              string
	Provider          string
	Model             string
	ReasoningEffort   string
	SkillsJson        []byte
	ToolsJson         []byte
	MaxRuntimeSeconds int32
	RetryPolicy       string
	MaxAttempts       int32
	ArchivedAt        pgtype.Timestamptz
	CreatedAt         pgtype.Timestamptz
	HasProviderKey    *bool
	ProviderID        *string
}

// Agents. The agent is the retry/limit source for every run it executes.
// Every mutable column UpdateAgent writes is written here too. The two drifted
// once: `reasoning_effort` was bound only by UpdateAgent, so a client's value
// was dropped in silence on create. internal/store/queries_columns_test.go is
// the guard that keeps the two lists in step.
//
// provider_id is the registry reference (US-AD109). It is written here for the
// same reason as everything else on this list: a create that omits it leaves
// the agent pointing at no provider, which phase 5 reads as "no credential".
func (q *Queries) CreateAgent(ctx context.Context, arg CreateAgentParams) (CreateAgentRow, error) {
	row := q.db.QueryRow(ctx, createAgent,
		arg.ID,
		arg.OrgID,
		arg.ProjectID,
		arg.Name,
		arg.Provider,
		arg.Model,
		arg.ReasoningEffort,
		arg.SkillsJson,
		arg.ToolsJson,
		arg.MaxRuntimeSeconds,
		arg.RetryPolicy,
		arg.MaxAttempts,
		arg.ProviderID,
	)
	var i CreateAgentRow
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ProjectID,
		&i.Name,
		&i.Provider,
		&i.Model,
		&i.ReasoningEffort,
		&i.SkillsJson,
		&i.ToolsJson,
		&i.MaxRuntimeSeconds,
		&i.RetryPolicy,
		&i.MaxAttempts,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.HasProviderKey,
		&i.ProviderID,
	)
	return i, err
}

const createAgentSkill = `-- name: CreateAgentSkill :one

INSERT INTO agent_skills (id, org_id, slug, name, body_md, is_system, created_by)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, org_id, slug, name, body_md, version, is_system, created_by, created_at, updated_at
`

type CreateAgentSkillParams struct {
	ID        string
	OrgID     string
	Slug      string
	Name      string
	BodyMd    string
	IsSystem  bool
	CreatedBy *string
}

// Agent skills (US-AD107). Skill is org-scoped data: users read and edit the
// markdown, agents only read it. Nothing here exposes a write path an agent
// could reach, and every query carries org_id explicitly.
func (q *Queries) CreateAgentSkill(ctx context.Context, arg CreateAgentSkillParams) (AgentSkill, error) {
	row := q.db.QueryRow(ctx, createAgentSkill,
		arg.ID,
		arg.OrgID,
		arg.Slug,
		arg.Name,
		arg.BodyMd,
		arg.IsSystem,
		arg.CreatedBy,
	)
	var i AgentSkill
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Slug,
		&i.Name,
		&i.BodyMd,
		&i.Version,
		&i.IsSystem,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createBoard = `-- name: CreateBoard :one
INSERT INTO boards (id, org_id, project_id, slug, name, columns_json, budget_daily_micros)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, org_id, project_id, slug, name, columns_json, budget_daily_micros, created_at
`

type CreateBoardParams struct {
	ID                string
	OrgID             string
	ProjectID         string
	Slug              string
	Name              string
	ColumnsJson       []byte
	BudgetDailyMicros int64
}

// Boards. columns_json is the board's view of status, never a new status.
func (q *Queries) CreateBoard(ctx context.Context, arg CreateBoardParams) (Board, error) {
	row := q.db.QueryRow(ctx, createBoard,
		arg.ID,
		arg.OrgID,
		arg.ProjectID,
		arg.Slug,
		arg.Name,
		arg.ColumnsJson,
		arg.BudgetDailyMicros,
	)
	var i Board
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ProjectID,
		&i.Slug,
		&i.Name,
		&i.ColumnsJson,
		&i.BudgetDailyMicros,
		&i.CreatedAt,
	)
	return i, err
}

const createEvent = `-- name: CreateEvent :one
INSERT INTO events (org_id, board_id, task_id, run_id, kind, payload_json)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, org_id, board_id, task_id, run_id, kind, payload_json, created_at
`

type CreateEventParams struct {
	OrgID       string
	BoardID     *string
	TaskID      *string
	RunID       *string
	Kind        string
	PayloadJson []byte
}

// Append-only event log. No UPDATE or DELETE is ever issued against events.
func (q *Queries) CreateEvent(ctx context.Context, arg CreateEventParams) (Event, error) {
	row := q.db.QueryRow(ctx, createEvent,
		arg.OrgID,
		arg.BoardID,
		arg.TaskID,
		arg.RunID,
		arg.Kind,
		arg.PayloadJson,
	)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.BoardID,
		&i.TaskID,
		&i.RunID,
		&i.Kind,
		&i.PayloadJson,
		&i.CreatedAt,
	)
	return i, err
}

const createMembership = `-- name: CreateMembership :exec
INSERT INTO memberships (org_id, user_id, role)
VALUES ($1, $2, $3)
ON CONFLICT (org_id, user_id) DO UPDATE
SET role = EXCLUDED.role
`

type CreateMembershipParams struct {
	OrgID  string
	UserID string
	Role   string
}

func (q *Queries) CreateMembership(ctx context.Context, arg CreateMembershipParams) error {
	_, err := q.db.Exec(ctx, createMembership, arg.OrgID, arg.UserID, arg.Role)
	return err
}

const createOrg = `-- name: CreateOrg :one
INSERT INTO orgs (id, slug, name)
VALUES ($1, $2, $3)
RETURNING id, slug, name, created_at
`

type CreateOrgParams struct {
	ID   string
	Slug string
	Name string
}

func (q *Queries) CreateOrg(ctx context.Context, arg CreateOrgParams) (Org, error) {
	row := q.db.QueryRow(ctx, createOrg, arg.ID, arg.Slug, arg.Name)
	var i Org
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}

const createOrgKind = `-- name: CreateOrgKind :exec
INSERT INTO org_kinds (org_id, kind)
VALUES ($1, $2)
`

type CreateOrgKindParams struct {
	OrgID string
	Kind  string
}

func (q *Queries) CreateOrgKind(ctx context.Context, arg CreateOrgKindParams) error {
	_, err := q.db.Exec(ctx, createOrgKind, arg.OrgID, arg.Kind)
	return err
}

const createProject = `-- name: CreateProject :one

INSERT INTO projects (id, org_id, slug, name)
VALUES ($1, $2, $3, $4)
RETURNING id, org_id, slug, name, created_at
`

type CreateProjectParams struct {
	ID    string
	OrgID string
	Slug  string
	Name  string
}

// ============================================================================
// M1 — projects, boards, agents, tasks, task_links, events
//
// Tenant scoping rule (ARCHITECTURE 17): every query below that touches an
// org-scoped row carries org_id explicitly, even when the id alone would be
// unique. There is no second code path that could forget the scope.
// ============================================================================
func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, createProject,
		arg.ID,
		arg.OrgID,
		arg.Slug,
		arg.Name,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Slug,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}

const createProvider = `-- name: CreateProvider :one

INSERT INTO providers (id, org_id, name, protocol, base_url, api_key_enc, is_default)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, org_id, name, protocol, base_url, api_key_enc, models_json,
          models_fetched_at, last_verified_at, is_default, created_at
`

type CreateProviderParams struct {
	ID        string
	OrgID     string
	Name      string
	Protocol  string
	BaseUrl   string
	ApiKeyEnc []byte
	IsDefault bool
}

// Providers (US-AD109, DECISIONS 6A.J). The credential and the address live
// here, once per workspace, instead of once per agent: agents point at a
// provider row, so one edit reaches every agent that uses it (AC6). Every query
// carries org_id explicitly, like the rest of this file.
func (q *Queries) CreateProvider(ctx context.Context, arg CreateProviderParams) (Provider, error) {
	row := q.db.QueryRow(ctx, createProvider,
		arg.ID,
		arg.OrgID,
		arg.Name,
		arg.Protocol,
		arg.BaseUrl,
		arg.ApiKeyEnc,
		arg.IsDefault,
	)
	var i Provider
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Protocol,
		&i.BaseUrl,
		&i.ApiKeyEnc,
		&i.ModelsJson,
		&i.ModelsFetchedAt,
		&i.LastVerifiedAt,
		&i.IsDefault,
		&i.CreatedAt,
	)
	return i, err
}

const createSession = `-- name: CreateSession :exec
INSERT INTO sessions (id, user_id, token_hash, expires_at, last_seen_at, created_at)
VALUES ($1, $2, $3, $4, $5, $6)
`

type CreateSessionParams struct {
	ID         string
	UserID     string
	TokenHash  string
	ExpiresAt  pgtype.Timestamptz
	LastSeenAt pgtype.Timestamptz
	CreatedAt  pgtype.Timestamptz
}

// token_hash is SHA-256 of the 64-byte raw token; the raw token only ever
// exists in the Set-Cookie (ARCHITECTURE 3.19).
func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) error {
	_, err := q.db.Exec(ctx, createSession,
		arg.ID,
		arg.UserID,
		arg.TokenHash,
		arg.ExpiresAt,
		arg.LastSeenAt,
		arg.CreatedAt,
	)
	return err
}

const createTask = `-- name: CreateTask :one
INSERT INTO tasks (id, org_id, board_id, title, body, status, priority, assignee_agent_id,
                   created_by, idempotency_key, workspace_kind, goal_mode, goal_max_turns)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13)
RETURNING id, org_id, board_id, title, body, status, priority, assignee_agent_id, created_by,
          idempotency_key, block_kind, consecutive_failures, workspace_kind, workspace_path,
          branch_name, completion_contract, goal_mode, goal_max_turns, current_run_id,
          cost_micros, tokens_in, tokens_out, created_at, started_at, completed_at, archived_at
`

type CreateTaskParams struct {
	ID              string
	OrgID           string
	BoardID         string
	Title           string
	Body            string
	Status          string
	Priority        int16
	AssigneeAgentID *string
	CreatedBy       string
	IdempotencyKey  *string
	WorkspaceKind   string
	GoalMode        string
	GoalMaxTurns    int32
}

// Tasks. created_by is the acting user; assignee_agent_id is nullable.
func (q *Queries) CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error) {
	row := q.db.QueryRow(ctx, createTask,
		arg.ID,
		arg.OrgID,
		arg.BoardID,
		arg.Title,
		arg.Body,
		arg.Status,
		arg.Priority,
		arg.AssigneeAgentID,
		arg.CreatedBy,
		arg.IdempotencyKey,
		arg.WorkspaceKind,
		arg.GoalMode,
		arg.GoalMaxTurns,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.BoardID,
		&i.Title,
		&i.Body,
		&i.Status,
		&i.Priority,
		&i.AssigneeAgentID,
		&i.CreatedBy,
		&i.IdempotencyKey,
		&i.BlockKind,
		&i.ConsecutiveFailures,
		&i.WorkspaceKind,
		&i.WorkspacePath,
		&i.BranchName,
		&i.CompletionContract,
		&i.GoalMode,
		&i.GoalMaxTurns,
		&i.CurrentRunID,
		&i.CostMicros,
		&i.TokensIn,
		&i.TokensOut,
		&i.CreatedAt,
		&i.StartedAt,
		&i.CompletedAt,
		&i.ArchivedAt,
	)
	return i, err
}

const createTaskLink = `-- name: CreateTaskLink :exec
INSERT INTO task_links (parent_id, child_id)
VALUES ($1, $2)
ON CONFLICT (parent_id, child_id) DO NOTHING
`

type CreateTaskLinkParams struct {
	ParentID string
	ChildID  string
}

// Dependency DAG. Self-links are rejected by the table CHECK, and the service
// rejects cycles before insert.
func (q *Queries) CreateTaskLink(ctx context.Context, arg CreateTaskLinkParams) error {
	_, err := q.db.Exec(ctx, createTaskLink, arg.ParentID, arg.ChildID)
	return err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (id, email, name, password_hash, is_shadow)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, email, name, password_hash, avatar_url, is_shadow, deleted_at, created_at
`

type CreateUserParams struct {
	ID           string
	Email        string
	Name         string
	PasswordHash string
	IsShadow     bool
}

type CreateUserRow struct {
	ID           string
	Email        string
	Name         string
	PasswordHash string
	AvatarURL    *string
	IsShadow     bool
	DeletedAt    pgtype.Timestamptz
	CreatedAt    pgtype.Timestamptz
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.ID,
		arg.Email,
		arg.Name,
		arg.PasswordHash,
		arg.IsShadow,
	)
	var i CreateUserRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.PasswordHash,
		&i.AvatarURL,
		&i.IsShadow,
		&i.DeletedAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteAgent = `-- name: DeleteAgent :exec
DELETE FROM agents WHERE id = $1 AND org_id = $2
`

type DeleteAgentParams struct {
	ID    string
	OrgID string
}

func (q *Queries) DeleteAgent(ctx context.Context, arg DeleteAgentParams) error {
	_, err := q.db.Exec(ctx, deleteAgent, arg.ID, arg.OrgID)
	return err
}

const deleteAgentSkill = `-- name: DeleteAgentSkill :exec
DELETE FROM agent_skills WHERE id = $1 AND org_id = $2 AND is_system = false
`

type DeleteAgentSkillParams struct {
	ID    string
	OrgID string
}

// System skills are not deletable: they are the baseline every workspace starts
// from, and removing one would silently strip capability from existing agents.
func (q *Queries) DeleteAgentSkill(ctx context.Context, arg DeleteAgentSkillParams) error {
	_, err := q.db.Exec(ctx, deleteAgentSkill, arg.ID, arg.OrgID)
	return err
}

const deleteBoard = `-- name: DeleteBoard :exec
DELETE FROM boards
WHERE id = $1 AND org_id = $2
`

type DeleteBoardParams struct {
	ID    string
	OrgID string
}

func (q *Queries) DeleteBoard(ctx context.Context, arg DeleteBoardParams) error {
	_, err := q.db.Exec(ctx, deleteBoard, arg.ID, arg.OrgID)
	return err
}

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :exec
DELETE FROM sessions
WHERE expires_at < now()
`

func (q *Queries) DeleteExpiredSessions(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredSessions)
	return err
}

const deleteMembership = `-- name: DeleteMembership :exec
DELETE FROM memberships
WHERE org_id = $1 AND user_id = $2
`

type DeleteMembershipParams struct {
	OrgID  string
	UserID string
}

func (q *Queries) DeleteMembership(ctx context.Context, arg DeleteMembershipParams) error {
	_, err := q.db.Exec(ctx, deleteMembership, arg.OrgID, arg.UserID)
	return err
}

const deleteProject = `-- name: DeleteProject :exec
DELETE FROM projects
WHERE id = $1 AND org_id = $2
`

type DeleteProjectParams struct {
	ID    string
	OrgID string
}

func (q *Queries) DeleteProject(ctx context.Context, arg DeleteProjectParams) error {
	_, err := q.db.Exec(ctx, deleteProject, arg.ID, arg.OrgID)
	return err
}

const deleteProvider = `-- name: DeleteProvider :exec
DELETE FROM providers WHERE id = $1 AND org_id = $2
`

type DeleteProviderParams struct {
	ID    string
	OrgID string
}

func (q *Queries) DeleteProvider(ctx context.Context, arg DeleteProviderParams) error {
	_, err := q.db.Exec(ctx, deleteProvider, arg.ID, arg.OrgID)
	return err
}

const deleteSessionByTokenHash = `-- name: DeleteSessionByTokenHash :exec
UPDATE sessions
SET deleted_at = now()
WHERE token_hash = $1 AND deleted_at IS NULL
`

func (q *Queries) DeleteSessionByTokenHash(ctx context.Context, tokenHash string) error {
	_, err := q.db.Exec(ctx, deleteSessionByTokenHash, tokenHash)
	return err
}

const deleteTask = `-- name: DeleteTask :exec
DELETE FROM tasks
WHERE id = $1 AND org_id = $2
`

type DeleteTaskParams struct {
	ID    string
	OrgID string
}

func (q *Queries) DeleteTask(ctx context.Context, arg DeleteTaskParams) error {
	_, err := q.db.Exec(ctx, deleteTask, arg.ID, arg.OrgID)
	return err
}

const deleteTaskLink = `-- name: DeleteTaskLink :exec
DELETE FROM task_links
WHERE parent_id = $1 AND child_id = $2
`

type DeleteTaskLinkParams struct {
	ParentID string
	ChildID  string
}

func (q *Queries) DeleteTaskLink(ctx context.Context, arg DeleteTaskLinkParams) error {
	_, err := q.db.Exec(ctx, deleteTaskLink, arg.ParentID, arg.ChildID)
	return err
}

const getAgent = `-- name: GetAgent :one
SELECT id, org_id, project_id, name, provider, model, reasoning_effort, skills_json,
       tools_json, max_runtime_seconds, retry_policy, max_attempts,
       archived_at, created_at, has_provider_key, provider_id
FROM agents
WHERE id = $1 AND org_id = $2
`

type GetAgentParams struct {
	ID    string
	OrgID string
}

type GetAgentRow struct {
	ID                string
	OrgID             string
	ProjectID         string
	Name              string
	Provider          string
	Model             string
	ReasoningEffort   string
	SkillsJson        []byte
	ToolsJson         []byte
	MaxRuntimeSeconds int32
	RetryPolicy       string
	MaxAttempts       int32
	ArchivedAt        pgtype.Timestamptz
	CreatedAt         pgtype.Timestamptz
	HasProviderKey    *bool
	ProviderID        *string
}

func (q *Queries) GetAgent(ctx context.Context, arg GetAgentParams) (GetAgentRow, error) {
	row := q.db.QueryRow(ctx, getAgent, arg.ID, arg.OrgID)
	var i GetAgentRow
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ProjectID,
		&i.Name,
		&i.Provider,
		&i.Model,
		&i.ReasoningEffort,
		&i.SkillsJson,
		&i.ToolsJson,
		&i.MaxRuntimeSeconds,
		&i.RetryPolicy,
		&i.MaxAttempts,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.HasProviderKey,
		&i.ProviderID,
	)
	return i, err
}

const getAgentProviderKey = `-- name: GetAgentProviderKey :one
SELECT provider_api_key_enc
FROM agents
WHERE id = $1 AND org_id = $2
`

type GetAgentProviderKeyParams struct {
	ID    string
	OrgID string
}

// The ONLY reader of the ciphertext column. Returns it alone so the sealed bytes
// never travel inside a struct that gets logged, cached, or serialised.
func (q *Queries) GetAgentProviderKey(ctx context.Context, arg GetAgentProviderKeyParams) ([]byte, error) {
	row := q.db.QueryRow(ctx, getAgentProviderKey, arg.ID, arg.OrgID)
	var provider_api_key_enc []byte
	err := row.Scan(&provider_api_key_enc)
	return provider_api_key_enc, err
}

const getAgentSkill = `-- name: GetAgentSkill :one
SELECT id, org_id, slug, name, body_md, version, is_system, created_by, created_at, updated_at
FROM agent_skills
WHERE id = $1 AND org_id = $2
`

type GetAgentSkillParams struct {
	ID    string
	OrgID string
}

func (q *Queries) GetAgentSkill(ctx context.Context, arg GetAgentSkillParams) (AgentSkill, error) {
	row := q.db.QueryRow(ctx, getAgentSkill, arg.ID, arg.OrgID)
	var i AgentSkill
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Slug,
		&i.Name,
		&i.BodyMd,
		&i.Version,
		&i.IsSystem,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getBoard = `-- name: GetBoard :one
SELECT id, org_id, project_id, slug, name, columns_json, budget_daily_micros, created_at
FROM boards
WHERE id = $1 AND org_id = $2
`

type GetBoardParams struct {
	ID    string
	OrgID string
}

func (q *Queries) GetBoard(ctx context.Context, arg GetBoardParams) (Board, error) {
	row := q.db.QueryRow(ctx, getBoard, arg.ID, arg.OrgID)
	var i Board
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ProjectID,
		&i.Slug,
		&i.Name,
		&i.ColumnsJson,
		&i.BudgetDailyMicros,
		&i.CreatedAt,
	)
	return i, err
}

const getMembership = `-- name: GetMembership :one
SELECT org_id, user_id, role, created_at
FROM memberships
WHERE org_id = $1 AND user_id = $2
`

type GetMembershipParams struct {
	OrgID  string
	UserID string
}

// The single membership row that answers "is this user in this org, and as
// what". Every org-scoped handler resolves its tenant through this query, so
// there is no second code path that could forget the org_id scope.
func (q *Queries) GetMembership(ctx context.Context, arg GetMembershipParams) (Membership, error) {
	row := q.db.QueryRow(ctx, getMembership, arg.OrgID, arg.UserID)
	var i Membership
	err := row.Scan(
		&i.OrgID,
		&i.UserID,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}

const getOrgByID = `-- name: GetOrgByID :one
SELECT id, slug, name, created_at
FROM orgs
WHERE id = $1
`

func (q *Queries) GetOrgByID(ctx context.Context, id string) (Org, error) {
	row := q.db.QueryRow(ctx, getOrgByID, id)
	var i Org
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}

const getPersonalWorkspace = `-- name: GetPersonalWorkspace :one
SELECT o.id, o.slug, o.name, o.created_at
FROM org_kinds k
JOIN orgs o ON o.id = k.org_id
WHERE k.kind = 'registration'
  AND EXISTS (
      SELECT 1 FROM memberships m
      WHERE m.org_id = o.id
        AND m.user_id = $1
        AND m.role   = 'owner'
  )
`

// The registration-kind org where THIS user is the owner: that is the only
// shape that means "my personal workspace". Membership alone is not enough —
// an invitee is a member of someone else's registration-kind org, and
// resolving it here would hand them a workspace that is not theirs.
func (q *Queries) GetPersonalWorkspace(ctx context.Context, userID string) (Org, error) {
	row := q.db.QueryRow(ctx, getPersonalWorkspace, userID)
	var i Org
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}

const getProject = `-- name: GetProject :one
SELECT id, org_id, slug, name, created_at
FROM projects
WHERE id = $1 AND org_id = $2
`

type GetProjectParams struct {
	ID    string
	OrgID string
}

func (q *Queries) GetProject(ctx context.Context, arg GetProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, getProject, arg.ID, arg.OrgID)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Slug,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}

const getProvider = `-- name: GetProvider :one
SELECT id, org_id, name, protocol, base_url, api_key_enc, models_json,
       models_fetched_at, last_verified_at, is_default, created_at
FROM providers
WHERE id = $1 AND org_id = $2
`

type GetProviderParams struct {
	ID    string
	OrgID string
}

// Returns api_key_enc because the handler layer is what decrypts, and it needs
// the sealed bytes to do so. Nothing in this file puts them in a response.
func (q *Queries) GetProvider(ctx context.Context, arg GetProviderParams) (Provider, error) {
	row := q.db.QueryRow(ctx, getProvider, arg.ID, arg.OrgID)
	var i Provider
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Protocol,
		&i.BaseUrl,
		&i.ApiKeyEnc,
		&i.ModelsJson,
		&i.ModelsFetchedAt,
		&i.LastVerifiedAt,
		&i.IsDefault,
		&i.CreatedAt,
	)
	return i, err
}

const getProviderKey = `-- name: GetProviderKey :one
SELECT api_key_enc FROM providers WHERE id = $1 AND org_id = $2
`

type GetProviderKeyParams struct {
	ID    string
	OrgID string
}

// The one query that hands out ciphertext, for the one path that decrypts it
// before probing an upstream (phase 3). Returning it as a scalar rather than as
// a column of GetProvider is deliberate: the domain Provider carries no
// ciphertext, so no read path can leak what it never receives.
// api_key_enc is nullable (a local endpoint that checks nothing), and a NULL
// scans into a nil []byte rather than an error.
func (q *Queries) GetProviderKey(ctx context.Context, arg GetProviderKeyParams) ([]byte, error) {
	row := q.db.QueryRow(ctx, getProviderKey, arg.ID, arg.OrgID)
	var api_key_enc []byte
	err := row.Scan(&api_key_enc)
	return api_key_enc, err
}

const getSessionByTokenHash = `-- name: GetSessionByTokenHash :one
SELECT id, user_id, token_hash, last_seen_at, expires_at, created_at
FROM sessions
WHERE token_hash = $1
  AND deleted_at IS NULL
  AND expires_at > now()
  AND last_seen_at > now() - ($2::interval)
`

type GetSessionByTokenHashParams struct {
	TokenHash string
	Column2   pgtype.Interval
}

type GetSessionByTokenHashRow struct {
	ID         string
	UserID     string
	TokenHash  string
	LastSeenAt pgtype.Timestamptz
	ExpiresAt  pgtype.Timestamptz
	CreatedAt  pgtype.Timestamptz
}

// Sliding idle window (US-AD02 AC4): a session that has been idle longer than
// the idle timeout is rejected, so last_seen_at is bumped on every use.
func (q *Queries) GetSessionByTokenHash(ctx context.Context, arg GetSessionByTokenHashParams) (GetSessionByTokenHashRow, error) {
	row := q.db.QueryRow(ctx, getSessionByTokenHash, arg.TokenHash, arg.Column2)
	var i GetSessionByTokenHashRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.LastSeenAt,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const getTask = `-- name: GetTask :one
SELECT id, org_id, board_id, title, body, status, priority, assignee_agent_id, created_by,
       idempotency_key, block_kind, consecutive_failures, workspace_kind, workspace_path,
       branch_name, completion_contract, goal_mode, goal_max_turns, current_run_id,
       cost_micros, tokens_in, tokens_out, created_at, started_at, completed_at, archived_at
FROM tasks
WHERE id = $1 AND org_id = $2
`

type GetTaskParams struct {
	ID    string
	OrgID string
}

func (q *Queries) GetTask(ctx context.Context, arg GetTaskParams) (Task, error) {
	row := q.db.QueryRow(ctx, getTask, arg.ID, arg.OrgID)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.BoardID,
		&i.Title,
		&i.Body,
		&i.Status,
		&i.Priority,
		&i.AssigneeAgentID,
		&i.CreatedBy,
		&i.IdempotencyKey,
		&i.BlockKind,
		&i.ConsecutiveFailures,
		&i.WorkspaceKind,
		&i.WorkspacePath,
		&i.BranchName,
		&i.CompletionContract,
		&i.GoalMode,
		&i.GoalMaxTurns,
		&i.CurrentRunID,
		&i.CostMicros,
		&i.TokensIn,
		&i.TokensOut,
		&i.CreatedAt,
		&i.StartedAt,
		&i.CompletedAt,
		&i.ArchivedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, name, password_hash, avatar_url, is_shadow, deleted_at, created_at
FROM users
WHERE lower(email) = lower($1) AND deleted_at IS NULL
`

type GetUserByEmailRow struct {
	ID           string
	Email        string
	Name         string
	PasswordHash string
	AvatarURL    *string
	IsShadow     bool
	DeletedAt    pgtype.Timestamptz
	CreatedAt    pgtype.Timestamptz
}

func (q *Queries) GetUserByEmail(ctx context.Context, lower string) (GetUserByEmailRow, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, lower)
	var i GetUserByEmailRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.PasswordHash,
		&i.AvatarURL,
		&i.IsShadow,
		&i.DeletedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, name, password_hash, avatar_url, is_shadow, deleted_at, created_at
FROM users
WHERE id = $1 AND deleted_at IS NULL
`

type GetUserByIDRow struct {
	ID           string
	Email        string
	Name         string
	PasswordHash string
	AvatarURL    *string
	IsShadow     bool
	DeletedAt    pgtype.Timestamptz
	CreatedAt    pgtype.Timestamptz
}

func (q *Queries) GetUserByID(ctx context.Context, id string) (GetUserByIDRow, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i GetUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.PasswordHash,
		&i.AvatarURL,
		&i.IsShadow,
		&i.DeletedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listAgentSkillsWithUsage = `-- name: ListAgentSkillsWithUsage :many
SELECT s.id, s.org_id, s.slug, s.name, s.body_md, s.version, s.is_system, s.created_by,
       s.created_at, s.updated_at,
       (SELECT count(*) FROM agents a
         WHERE a.org_id = s.org_id AND a.archived_at IS NULL AND a.skills_json ? s.slug) AS used_by
FROM agent_skills s
WHERE s.org_id = $1
ORDER BY s.is_system DESC, s.slug
`

type ListAgentSkillsWithUsageRow struct {
	ID        string
	OrgID     string
	Slug      string
	Name      string
	BodyMd    string
	Version   int32
	IsSystem  bool
	CreatedBy *string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
	UsedBy    int64
}

// The list needs "dipakai N agent" on every row, so usage is resolved in the
// same round trip: a per-row query would be N+1 against a table the user scrolls.
// `?` is jsonb containment for a top-level array element, i.e. the slug is in
// agents.skills_json. Archived agents are excluded: they no longer receive work,
// so they must not make a skill look live.
func (q *Queries) ListAgentSkillsWithUsage(ctx context.Context, orgID string) ([]ListAgentSkillsWithUsageRow, error) {
	rows, err := q.db.Query(ctx, listAgentSkillsWithUsage, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAgentSkillsWithUsageRow
	for rows.Next() {
		var i ListAgentSkillsWithUsageRow
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Slug,
			&i.Name,
			&i.BodyMd,
			&i.Version,
			&i.IsSystem,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UsedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAgents = `-- name: ListAgents :many
SELECT id, org_id, project_id, name, provider, model, reasoning_effort, skills_json,
       tools_json, max_runtime_seconds, retry_policy, max_attempts,
       archived_at, created_at, has_provider_key, provider_id
FROM agents
WHERE org_id = $1 AND project_id = $2
ORDER BY name
`

type ListAgentsParams struct {
	OrgID     string
	ProjectID string
}

type ListAgentsRow struct {
	ID                string
	OrgID             string
	ProjectID         string
	Name              string
	Provider          string
	Model             string
	ReasoningEffort   string
	SkillsJson        []byte
	ToolsJson         []byte
	MaxRuntimeSeconds int32
	RetryPolicy       string
	MaxAttempts       int32
	ArchivedAt        pgtype.Timestamptz
	CreatedAt         pgtype.Timestamptz
	HasProviderKey    *bool
	ProviderID        *string
}

// Returns archived rows too, deliberately. The registry is where a user finds an
// agent again to unarchive it, so filtering them out here would make archiving
// irreversible from the UI. Callers that must not offer a retired agent (the
// assign dropdown, US-AD73 AC2) filter on `archived_at` themselves — see
// ListAgentsUsingSkill and the task-assign path.
func (q *Queries) ListAgents(ctx context.Context, arg ListAgentsParams) ([]ListAgentsRow, error) {
	rows, err := q.db.Query(ctx, listAgents, arg.OrgID, arg.ProjectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAgentsRow
	for rows.Next() {
		var i ListAgentsRow
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.ProjectID,
			&i.Name,
			&i.Provider,
			&i.Model,
			&i.ReasoningEffort,
			&i.SkillsJson,
			&i.ToolsJson,
			&i.MaxRuntimeSeconds,
			&i.RetryPolicy,
			&i.MaxAttempts,
			&i.ArchivedAt,
			&i.CreatedAt,
			&i.HasProviderKey,
			&i.ProviderID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAgentsUsingProvider = `-- name: ListAgentsUsingProvider :many
SELECT id, name FROM agents
WHERE org_id = $1 AND provider_id = $2
ORDER BY name
`

type ListAgentsUsingProviderParams struct {
	OrgID      string
	ProviderID *string
}

type ListAgentsUsingProviderRow struct {
	ID   string
	Name string
}

// AC5: the 409 has to name the agents pinning this provider, so this is a read
// of names the caller can already list, not a count.
func (q *Queries) ListAgentsUsingProvider(ctx context.Context, arg ListAgentsUsingProviderParams) ([]ListAgentsUsingProviderRow, error) {
	rows, err := q.db.Query(ctx, listAgentsUsingProvider, arg.OrgID, arg.ProviderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAgentsUsingProviderRow
	for rows.Next() {
		var i ListAgentsUsingProviderRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAgentsUsingSkill = `-- name: ListAgentsUsingSkill :many
SELECT id, name FROM agents
WHERE org_id = $1 AND archived_at IS NULL AND skills_json ? $2
ORDER BY name
`

type ListAgentsUsingSkillParams struct {
	OrgID      string
	SkillsJson []byte
}

type ListAgentsUsingSkillRow struct {
	ID   string
	Name string
}

// Feeds the "dipakai oleh" list under the editor; each name routes to the agent
// detail page, which is what stops a user from editing a live skill blindly.
func (q *Queries) ListAgentsUsingSkill(ctx context.Context, arg ListAgentsUsingSkillParams) ([]ListAgentsUsingSkillRow, error) {
	rows, err := q.db.Query(ctx, listAgentsUsingSkill, arg.OrgID, arg.SkillsJson)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAgentsUsingSkillRow
	for rows.Next() {
		var i ListAgentsUsingSkillRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAssignableAgents = `-- name: ListAssignableAgents :many
SELECT id, org_id, project_id, name, provider, model, reasoning_effort, skills_json,
       tools_json, max_runtime_seconds, retry_policy, max_attempts,
       archived_at, created_at, has_provider_key, provider_id
FROM agents
WHERE org_id = $1 AND archived_at IS NULL
ORDER BY name
`

type ListAssignableAgentsRow struct {
	ID                string
	OrgID             string
	ProjectID         string
	Name              string
	Provider          string
	Model             string
	ReasoningEffort   string
	SkillsJson        []byte
	ToolsJson         []byte
	MaxRuntimeSeconds int32
	RetryPolicy       string
	MaxAttempts       int32
	ArchivedAt        pgtype.Timestamptz
	CreatedAt         pgtype.Timestamptz
	HasProviderKey    *bool
	ProviderID        *string
}

// US-AD73 AC2: the assign dropdown must never offer a retired agent. This is the
// deliberate counterpart to ListAgents, which returns archived rows so the
// registry can unarchive them.
func (q *Queries) ListAssignableAgents(ctx context.Context, orgID string) ([]ListAssignableAgentsRow, error) {
	rows, err := q.db.Query(ctx, listAssignableAgents, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAssignableAgentsRow
	for rows.Next() {
		var i ListAssignableAgentsRow
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.ProjectID,
			&i.Name,
			&i.Provider,
			&i.Model,
			&i.ReasoningEffort,
			&i.SkillsJson,
			&i.ToolsJson,
			&i.MaxRuntimeSeconds,
			&i.RetryPolicy,
			&i.MaxAttempts,
			&i.ArchivedAt,
			&i.CreatedAt,
			&i.HasProviderKey,
			&i.ProviderID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAssignableAgentsForBoard = `-- name: ListAssignableAgentsForBoard :many
SELECT a.id,
       a.name,
       (CASE WHEN a.provider_id IS NULL THEN a.has_provider_key
             ELSE COALESCE(p.api_key_enc IS NOT NULL, false) END)::boolean AS has_provider_key
FROM agents a
JOIN boards b ON b.project_id = a.project_id AND b.org_id = a.org_id
LEFT JOIN providers p ON p.id = a.provider_id AND p.org_id = a.org_id
WHERE a.org_id = $1 AND b.id = $2 AND a.archived_at IS NULL
ORDER BY a.name
`

type ListAssignableAgentsForBoardParams struct {
	OrgID string
	ID    string
}

type ListAssignableAgentsForBoardRow struct {
	ID             string
	Name           string
	HasProviderKey bool
}

// The real assign picker for a board: every active agent of the board's own
// project, ordered the way the picker shows them. It is the source of the
// preview's "Filter Active Only" claim, so the section proves AC2 against the
// same rows the task-create modal would offer.
// `has_provider_key` here is the PROVIDER's key, not the agent's column. DECISIONS
// 6A.J moved credentials to `providers` ("sekali per ruang kerja, dirujuk banyak
// agent") and US-AD109 AC6 says the agent keeps no copy, so reading
// `a.has_provider_key` would mark an agent unready while its provider holds a
// working key. An agent with no provider row keeps its own column as the answer:
// nothing else can hold a credential for it. This is the same rule the registry
// and the agent detail apply (frontend `agentState`).
func (q *Queries) ListAssignableAgentsForBoard(ctx context.Context, arg ListAssignableAgentsForBoardParams) ([]ListAssignableAgentsForBoardRow, error) {
	rows, err := q.db.Query(ctx, listAssignableAgentsForBoard, arg.OrgID, arg.ID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAssignableAgentsForBoardRow
	for rows.Next() {
		var i ListAssignableAgentsForBoardRow
		if err := rows.Scan(&i.ID, &i.Name, &i.HasProviderKey); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAssignedTasks = `-- name: ListAssignedTasks :many
SELECT id, board_id, title, status, cost_micros, created_at
FROM tasks
WHERE org_id = $1 AND assignee_agent_id = $2 AND status != 'archived'
ORDER BY (status = 'running') DESC, created_at DESC
`

type ListAssignedTasksParams struct {
	OrgID           string
	AssigneeAgentID *string
}

type ListAssignedTasksRow struct {
	ID         string
	BoardID    string
	Title      string
	Status     string
	CostMicros int64
	CreatedAt  pgtype.Timestamptz
}

// Dispatcher claim (ARCHITECTURE 4b): one atomic statement. SKIP LOCKED lets
// concurrent dispatchers claim disjoint batches instead of serialising on the
// board row, and the status='ready' predicate means a second claimer sees an
// empty set rather than a duplicate claim.
// Screen 28-agent-detail draws the "simulasi penugasan" section: which tasks this
// agent holds, and the guarantee that archiving it does not cut a running one
// off (US-AD73 AC1). Archived tasks are excluded (they are gone from the board,
// like ListBoardTasks), and the order puts live work first so the running row is
// the one an operator sees without scrolling.
func (q *Queries) ListAssignedTasks(ctx context.Context, arg ListAssignedTasksParams) ([]ListAssignedTasksRow, error) {
	rows, err := q.db.Query(ctx, listAssignedTasks, arg.OrgID, arg.AssigneeAgentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAssignedTasksRow
	for rows.Next() {
		var i ListAssignedTasksRow
		if err := rows.Scan(
			&i.ID,
			&i.BoardID,
			&i.Title,
			&i.Status,
			&i.CostMicros,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBoardEventsAfter = `-- name: ListBoardEventsAfter :many
SELECT id, org_id, board_id, task_id, run_id, kind, payload_json, created_at
FROM events
WHERE board_id = $1 AND org_id = $2 AND id > $3
ORDER BY id
LIMIT $4
`

type ListBoardEventsAfterParams struct {
	BoardID *string
	OrgID   string
	ID      int64
	Limit   int32
}

// SSE resume: events newer than the client's Last-Event-ID for one board.
func (q *Queries) ListBoardEventsAfter(ctx context.Context, arg ListBoardEventsAfterParams) ([]Event, error) {
	rows, err := q.db.Query(ctx, listBoardEventsAfter,
		arg.BoardID,
		arg.OrgID,
		arg.ID,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Event
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.BoardID,
			&i.TaskID,
			&i.RunID,
			&i.Kind,
			&i.PayloadJson,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBoardTasks = `-- name: ListBoardTasks :many
SELECT id, org_id, board_id, title, body, status, priority, assignee_agent_id, created_by,
       idempotency_key, block_kind, consecutive_failures, workspace_kind, workspace_path,
       branch_name, completion_contract, goal_mode, goal_max_turns, current_run_id,
       cost_micros, tokens_in, tokens_out, created_at, started_at, completed_at, archived_at
FROM tasks
WHERE org_id = $1 AND board_id = $2 AND status != 'archived'
ORDER BY priority DESC, created_at DESC
`

type ListBoardTasksParams struct {
	OrgID   string
	BoardID string
}

func (q *Queries) ListBoardTasks(ctx context.Context, arg ListBoardTasksParams) ([]Task, error) {
	rows, err := q.db.Query(ctx, listBoardTasks, arg.OrgID, arg.BoardID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.BoardID,
			&i.Title,
			&i.Body,
			&i.Status,
			&i.Priority,
			&i.AssigneeAgentID,
			&i.CreatedBy,
			&i.IdempotencyKey,
			&i.BlockKind,
			&i.ConsecutiveFailures,
			&i.WorkspaceKind,
			&i.WorkspacePath,
			&i.BranchName,
			&i.CompletionContract,
			&i.GoalMode,
			&i.GoalMaxTurns,
			&i.CurrentRunID,
			&i.CostMicros,
			&i.TokensIn,
			&i.TokensOut,
			&i.CreatedAt,
			&i.StartedAt,
			&i.CompletedAt,
			&i.ArchivedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBoards = `-- name: ListBoards :many
SELECT id, org_id, project_id, slug, name, columns_json, budget_daily_micros, created_at
FROM boards
WHERE org_id = $1 AND project_id = $2
ORDER BY created_at DESC
`

type ListBoardsParams struct {
	OrgID     string
	ProjectID string
}

func (q *Queries) ListBoards(ctx context.Context, arg ListBoardsParams) ([]Board, error) {
	rows, err := q.db.Query(ctx, listBoards, arg.OrgID, arg.ProjectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Board
	for rows.Next() {
		var i Board
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.ProjectID,
			&i.Slug,
			&i.Name,
			&i.ColumnsJson,
			&i.BudgetDailyMicros,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMembers = `-- name: ListMembers :many
SELECT m.user_id, u.email, u.name, m.role, m.created_at
FROM memberships m
JOIN users u ON u.id = m.user_id
WHERE m.org_id = $1
ORDER BY m.created_at, u.email
`

type ListMembersRow struct {
	UserID    string
	Email     string
	Name      string
	Role      string
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) ListMembers(ctx context.Context, orgID string) ([]ListMembersRow, error) {
	rows, err := q.db.Query(ctx, listMembers, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMembersRow
	for rows.Next() {
		var i ListMembersRow
		if err := rows.Scan(
			&i.UserID,
			&i.Email,
			&i.Name,
			&i.Role,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrgsForUser = `-- name: ListOrgsForUser :many
SELECT m.org_id, o.slug, o.name, k.kind, m.role
FROM memberships m
JOIN orgs o ON o.id = m.org_id
LEFT JOIN org_kinds k ON k.org_id = m.org_id
WHERE m.user_id = $1
ORDER BY m.created_at
`

type ListOrgsForUserRow struct {
	OrgID string
	Slug  string
	Name  string
	Kind  *string
	Role  string
}

// The org roster a user belongs to, with their role in each. Scoping is
// by membership, not by the caller's guess of an org id, so this cannot
// leak a tenant the user is not part of (tenant isolation, ARCHITECTURE 17).
func (q *Queries) ListOrgsForUser(ctx context.Context, userID string) ([]ListOrgsForUserRow, error) {
	rows, err := q.db.Query(ctx, listOrgsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOrgsForUserRow
	for rows.Next() {
		var i ListOrgsForUserRow
		if err := rows.Scan(
			&i.OrgID,
			&i.Slug,
			&i.Name,
			&i.Kind,
			&i.Role,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjects = `-- name: ListProjects :many
SELECT id, org_id, slug, name, created_at
FROM projects
WHERE org_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListProjects(ctx context.Context, orgID string) ([]Project, error) {
	rows, err := q.db.Query(ctx, listProjects, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Project
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Slug,
			&i.Name,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProviders = `-- name: ListProviders :many
SELECT id, org_id, name, protocol, base_url, api_key_enc, models_json,
       models_fetched_at, last_verified_at, is_default, created_at
FROM providers
WHERE org_id = $1
ORDER BY is_default DESC, name
`

// The default sorts first because it is what the agent form preselects (AC9).
func (q *Queries) ListProviders(ctx context.Context, orgID string) ([]Provider, error) {
	rows, err := q.db.Query(ctx, listProviders, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Provider
	for rows.Next() {
		var i Provider
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Name,
			&i.Protocol,
			&i.BaseUrl,
			&i.ApiKeyEnc,
			&i.ModelsJson,
			&i.ModelsFetchedAt,
			&i.LastVerifiedAt,
			&i.IsDefault,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStaleProviderModels = `-- name: ListStaleProviderModels :many
SELECT id, org_id, name, protocol, base_url, api_key_enc, models_json,
       models_fetched_at, last_verified_at, is_default, created_at
FROM providers
WHERE models_fetched_at IS NULL OR models_fetched_at < $1
ORDER BY models_fetched_at NULLS FIRST, id
LIMIT $2
`

type ListStaleProviderModelsParams struct {
	Before  pgtype.Timestamptz
	MaxRows int32
}

// AC7's automatic half. This is the ONE provider query deliberately not scoped by
// org_id: the background refresher has no tenant in hand — it walks every
// workspace — so a `WHERE org_id = $1` here would make it impossible to write.
// Request-serving code must never call this; the reads that answer a user are
// List/Get, and both carry org_id.
//
// NULL models_fetched_at is stale, not fresh: "never fetched" is exactly the
// state that needs a fetch. The ORDER BY puts those first so a workspace that
// just registered a provider is served before one that merely aged out.
//
// The id tiebreaker makes the batch deterministic. Without it the order among
// equally-stale rows is unspecified, so with more stale providers than the batch
// cap the same subset can be chosen every pass and the rest starve.
// ponytail: deterministic is not the same as fair — a permanently broken provider
// stays stale forever and keeps its slot. Serving every workspace round-robin
// needs a last_attempt_at column; add it if a provider is ever observed never
// getting its turn.
func (q *Queries) ListStaleProviderModels(ctx context.Context, arg ListStaleProviderModelsParams) ([]Provider, error) {
	rows, err := q.db.Query(ctx, listStaleProviderModels, arg.Before, arg.MaxRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Provider
	for rows.Next() {
		var i Provider
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Name,
			&i.Protocol,
			&i.BaseUrl,
			&i.ApiKeyEnc,
			&i.ModelsJson,
			&i.ModelsFetchedAt,
			&i.LastVerifiedAt,
			&i.IsDefault,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTaskChildren = `-- name: ListTaskChildren :many
SELECT l.child_id, t.title, t.status
FROM task_links l
JOIN tasks t ON t.id = l.child_id
WHERE l.parent_id = $1
ORDER BY t.created_at
`

type ListTaskChildrenRow struct {
	ChildID string
	Title   string
	Status  string
}

func (q *Queries) ListTaskChildren(ctx context.Context, parentID string) ([]ListTaskChildrenRow, error) {
	rows, err := q.db.Query(ctx, listTaskChildren, parentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTaskChildrenRow
	for rows.Next() {
		var i ListTaskChildrenRow
		if err := rows.Scan(&i.ChildID, &i.Title, &i.Status); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTaskEvents = `-- name: ListTaskEvents :many
SELECT id, org_id, board_id, task_id, run_id, kind, payload_json, created_at
FROM events
WHERE task_id = $1
ORDER BY id
`

func (q *Queries) ListTaskEvents(ctx context.Context, taskID *string) ([]Event, error) {
	rows, err := q.db.Query(ctx, listTaskEvents, taskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Event
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.BoardID,
			&i.TaskID,
			&i.RunID,
			&i.Kind,
			&i.PayloadJson,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTaskParents = `-- name: ListTaskParents :many
SELECT l.parent_id, t.title, t.status
FROM task_links l
JOIN tasks t ON t.id = l.parent_id
WHERE l.child_id = $1
ORDER BY t.created_at
`

type ListTaskParentsRow struct {
	ParentID string
	Title    string
	Status   string
}

func (q *Queries) ListTaskParents(ctx context.Context, childID string) ([]ListTaskParentsRow, error) {
	rows, err := q.db.Query(ctx, listTaskParents, childID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTaskParentsRow
	for rows.Next() {
		var i ListTaskParentsRow
		if err := rows.Scan(&i.ParentID, &i.Title, &i.Status); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const renameOrgWithAudit = `-- name: RenameOrgWithAudit :exec
WITH renamed AS (
    UPDATE orgs
    SET name = $2
    WHERE id = $1
    RETURNING id
)
INSERT INTO audit_log (org_id, actor_user_id, action, target_type, target_id, before_json, after_json, ip)
SELECT $1, $3, 'org.rename', 'org', $1, $4::jsonb, $5::jsonb, $6
FROM renamed
`

type RenameOrgWithAuditParams struct {
	OrgID       string
	Name        string
	ActorUserID *string
	Column4     []byte
	Column5     []byte
	Ip          string
}

// Keep the rename and its audit row in one statement: if the INSERT fails, the
// data-modifying CTE is rolled back too (US-AD77 fail-closed).
func (q *Queries) RenameOrgWithAudit(ctx context.Context, arg RenameOrgWithAuditParams) error {
	_, err := q.db.Exec(ctx, renameOrgWithAudit,
		arg.OrgID,
		arg.Name,
		arg.ActorUserID,
		arg.Column4,
		arg.Column5,
		arg.Ip,
	)
	return err
}

const setAgentProviderKey = `-- name: SetAgentProviderKey :one
UPDATE agents
SET provider_api_key_enc = $3
WHERE id = $1 AND org_id = $2
RETURNING id, has_provider_key
`

type SetAgentProviderKeyParams struct {
	ID                string
	OrgID             string
	ProviderApiKeyEnc []byte
}

type SetAgentProviderKeyRow struct {
	ID             string
	HasProviderKey *bool
}

// US-AD86: store the sealed credential. Encryption/decryption lives in
// internal/crypto; this statement only ever sees ciphertext, so a DB dump alone
// cannot recover a provider key. Returning the derived flag lets the handler
// answer without a second round-trip.
func (q *Queries) SetAgentProviderKey(ctx context.Context, arg SetAgentProviderKeyParams) (SetAgentProviderKeyRow, error) {
	row := q.db.QueryRow(ctx, setAgentProviderKey, arg.ID, arg.OrgID, arg.ProviderApiKeyEnc)
	var i SetAgentProviderKeyRow
	err := row.Scan(&i.ID, &i.HasProviderKey)
	return i, err
}

const setProviderModels = `-- name: SetProviderModels :exec
UPDATE providers SET models_json = $3, models_fetched_at = $4
WHERE id = $1 AND org_id = $2
`

type SetProviderModelsParams struct {
	ID              string
	OrgID           string
	ModelsJson      []byte
	ModelsFetchedAt pgtype.Timestamptz
}

// AC7: the fetched list and the moment it was fetched, written together so a
// freshness check can never see one without the other.
func (q *Queries) SetProviderModels(ctx context.Context, arg SetProviderModelsParams) error {
	_, err := q.db.Exec(ctx, setProviderModels,
		arg.ID,
		arg.OrgID,
		arg.ModelsJson,
		arg.ModelsFetchedAt,
	)
	return err
}

const setProviderVerifiedAt = `-- name: SetProviderVerifiedAt :exec
UPDATE providers SET last_verified_at = $3
WHERE id = $1 AND org_id = $2
`

type SetProviderVerifiedAtParams struct {
	ID             string
	OrgID          string
	LastVerifiedAt pgtype.Timestamptz
}

// AC3: stamped only after the inference probe passes. Nothing else writes this
// column, so a non-null value always means a probe succeeded.
func (q *Queries) SetProviderVerifiedAt(ctx context.Context, arg SetProviderVerifiedAtParams) error {
	_, err := q.db.Exec(ctx, setProviderVerifiedAt, arg.ID, arg.OrgID, arg.LastVerifiedAt)
	return err
}

const touchSession = `-- name: TouchSession :exec
UPDATE sessions
SET last_seen_at = now()
WHERE token_hash = $1 AND deleted_at IS NULL
`

func (q *Queries) TouchSession(ctx context.Context, tokenHash string) error {
	_, err := q.db.Exec(ctx, touchSession, tokenHash)
	return err
}

const unarchiveAgent = `-- name: UnarchiveAgent :one
UPDATE agents
SET archived_at = NULL
WHERE id = $1 AND org_id = $2
RETURNING id, org_id, project_id, name, provider, model, reasoning_effort, skills_json,
          tools_json, max_runtime_seconds, retry_policy, max_attempts,
          archived_at, created_at, has_provider_key, provider_id
`

type UnarchiveAgentParams struct {
	ID    string
	OrgID string
}

type UnarchiveAgentRow struct {
	ID                string
	OrgID             string
	ProjectID         string
	Name              string
	Provider          string
	Model             string
	ReasoningEffort   string
	SkillsJson        []byte
	ToolsJson         []byte
	MaxRuntimeSeconds int32
	RetryPolicy       string
	MaxAttempts       int32
	ArchivedAt        pgtype.Timestamptz
	CreatedAt         pgtype.Timestamptz
	HasProviderKey    *bool
	ProviderID        *string
}

func (q *Queries) UnarchiveAgent(ctx context.Context, arg UnarchiveAgentParams) (UnarchiveAgentRow, error) {
	row := q.db.QueryRow(ctx, unarchiveAgent, arg.ID, arg.OrgID)
	var i UnarchiveAgentRow
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ProjectID,
		&i.Name,
		&i.Provider,
		&i.Model,
		&i.ReasoningEffort,
		&i.SkillsJson,
		&i.ToolsJson,
		&i.MaxRuntimeSeconds,
		&i.RetryPolicy,
		&i.MaxAttempts,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.HasProviderKey,
		&i.ProviderID,
	)
	return i, err
}

const updateAgent = `-- name: UpdateAgent :one
UPDATE agents
SET name = $3, provider = $4, model = $5, reasoning_effort = $6,
    skills_json = $7, tools_json = $8, max_runtime_seconds = $9,
    retry_policy = $10, max_attempts = $11, provider_id = $12
WHERE id = $1 AND org_id = $2
RETURNING id, org_id, project_id, name, provider, model, reasoning_effort, skills_json,
          tools_json, max_runtime_seconds, retry_policy, max_attempts,
          archived_at, created_at, has_provider_key, provider_id
`

type UpdateAgentParams struct {
	ID                string
	OrgID             string
	Name              string
	Provider          string
	Model             string
	ReasoningEffort   string
	SkillsJson        []byte
	ToolsJson         []byte
	MaxRuntimeSeconds int32
	RetryPolicy       string
	MaxAttempts       int32
	ProviderID        *string
}

type UpdateAgentRow struct {
	ID                string
	OrgID             string
	ProjectID         string
	Name              string
	Provider          string
	Model             string
	ReasoningEffort   string
	SkillsJson        []byte
	ToolsJson         []byte
	MaxRuntimeSeconds int32
	RetryPolicy       string
	MaxAttempts       int32
	ArchivedAt        pgtype.Timestamptz
	CreatedAt         pgtype.Timestamptz
	HasProviderKey    *bool
	ProviderID        *string
}

// US-AD96: the edit form replaces every mutable field at once, so this is a
// full update rather than a partial patch.
//
// provider_id is the registry reference (US-AD109). It is nullable and stays
// that way: an agent with no provider of its own uses the workspace default.
func (q *Queries) UpdateAgent(ctx context.Context, arg UpdateAgentParams) (UpdateAgentRow, error) {
	row := q.db.QueryRow(ctx, updateAgent,
		arg.ID,
		arg.OrgID,
		arg.Name,
		arg.Provider,
		arg.Model,
		arg.ReasoningEffort,
		arg.SkillsJson,
		arg.ToolsJson,
		arg.MaxRuntimeSeconds,
		arg.RetryPolicy,
		arg.MaxAttempts,
		arg.ProviderID,
	)
	var i UpdateAgentRow
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ProjectID,
		&i.Name,
		&i.Provider,
		&i.Model,
		&i.ReasoningEffort,
		&i.SkillsJson,
		&i.ToolsJson,
		&i.MaxRuntimeSeconds,
		&i.RetryPolicy,
		&i.MaxAttempts,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.HasProviderKey,
		&i.ProviderID,
	)
	return i, err
}

const updateAgentSkill = `-- name: UpdateAgentSkill :one
UPDATE agent_skills
SET name = $3, body_md = $4, version = version + 1, updated_at = now()
WHERE id = $1 AND org_id = $2
RETURNING id, org_id, slug, name, body_md, version, is_system, created_by, created_at, updated_at
`

type UpdateAgentSkillParams struct {
	ID     string
	OrgID  string
	Name   string
	BodyMd string
}

// AC6: version rises on every edit and older content is never rewritten in
// place, so a run that already loaded v3 keeps meaning what it meant.
func (q *Queries) UpdateAgentSkill(ctx context.Context, arg UpdateAgentSkillParams) (AgentSkill, error) {
	row := q.db.QueryRow(ctx, updateAgentSkill,
		arg.ID,
		arg.OrgID,
		arg.Name,
		arg.BodyMd,
	)
	var i AgentSkill
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Slug,
		&i.Name,
		&i.BodyMd,
		&i.Version,
		&i.IsSystem,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateBoardBudget = `-- name: UpdateBoardBudget :exec
UPDATE boards
SET budget_daily_micros = $3
WHERE id = $1 AND org_id = $2
`

type UpdateBoardBudgetParams struct {
	ID                string
	OrgID             string
	BudgetDailyMicros int64
}

func (q *Queries) UpdateBoardBudget(ctx context.Context, arg UpdateBoardBudgetParams) error {
	_, err := q.db.Exec(ctx, updateBoardBudget, arg.ID, arg.OrgID, arg.BudgetDailyMicros)
	return err
}

const updateBoardColumns = `-- name: UpdateBoardColumns :exec
UPDATE boards
SET columns_json = $3
WHERE id = $1 AND org_id = $2
`

type UpdateBoardColumnsParams struct {
	ID          string
	OrgID       string
	ColumnsJson []byte
}

func (q *Queries) UpdateBoardColumns(ctx context.Context, arg UpdateBoardColumnsParams) error {
	_, err := q.db.Exec(ctx, updateBoardColumns, arg.ID, arg.OrgID, arg.ColumnsJson)
	return err
}

const updateBoardName = `-- name: UpdateBoardName :exec
UPDATE boards
SET name = $3
WHERE id = $1 AND org_id = $2
`

type UpdateBoardNameParams struct {
	ID    string
	OrgID string
	Name  string
}

func (q *Queries) UpdateBoardName(ctx context.Context, arg UpdateBoardNameParams) error {
	_, err := q.db.Exec(ctx, updateBoardName, arg.ID, arg.OrgID, arg.Name)
	return err
}

const updateMembershipRole = `-- name: UpdateMembershipRole :exec
UPDATE memberships
SET role = $3
WHERE org_id = $1 AND user_id = $2
`

type UpdateMembershipRoleParams struct {
	OrgID  string
	UserID string
	Role   string
}

func (q *Queries) UpdateMembershipRole(ctx context.Context, arg UpdateMembershipRoleParams) error {
	_, err := q.db.Exec(ctx, updateMembershipRole, arg.OrgID, arg.UserID, arg.Role)
	return err
}

const updateOrgName = `-- name: UpdateOrgName :exec
UPDATE orgs
SET name = $2
WHERE id = $1
`

type UpdateOrgNameParams struct {
	ID   string
	Name string
}

func (q *Queries) UpdateOrgName(ctx context.Context, arg UpdateOrgNameParams) error {
	_, err := q.db.Exec(ctx, updateOrgName, arg.ID, arg.Name)
	return err
}

const updateProjectName = `-- name: UpdateProjectName :exec
UPDATE projects
SET name = $3
WHERE id = $1 AND org_id = $2
`

type UpdateProjectNameParams struct {
	ID    string
	OrgID string
	Name  string
}

func (q *Queries) UpdateProjectName(ctx context.Context, arg UpdateProjectNameParams) error {
	_, err := q.db.Exec(ctx, updateProjectName, arg.ID, arg.OrgID, arg.Name)
	return err
}

const updateProvider = `-- name: UpdateProvider :one
UPDATE providers
SET name        = COALESCE($1, name),
    protocol    = COALESCE($2, protocol),
    base_url    = COALESCE($3, base_url),
    api_key_enc = COALESCE($4, api_key_enc),
    is_default  = COALESCE($5, is_default)
WHERE id = $6 AND org_id = $7
RETURNING id, org_id, name, protocol, base_url, api_key_enc, models_json,
          models_fetched_at, last_verified_at, is_default, created_at
`

type UpdateProviderParams struct {
	Name      *string
	Protocol  *string
	BaseUrl   *string
	ApiKeyEnc []byte
	IsDefault *bool
	ID        string
	OrgID     string
}

// A partial update, deliberately — not the full-replace shape UpdateAgent uses.
// A full replace would blank every column the caller omitted, and three of them
// (models_json, models_fetched_at, last_verified_at) belong to phase 3: renaming
// a provider would silently erase its model list and its verification
// timestamp. COALESCE keeps whatever the request leaves out, and those three
// columns are not in the SET list at all.
//
// There is no way to clear api_key_enc here: passing NULL means "leave it", so
// a provider that has a credential keeps it. Removing a credential is not in
// the contract's seven endpoints.
func (q *Queries) UpdateProvider(ctx context.Context, arg UpdateProviderParams) (Provider, error) {
	row := q.db.QueryRow(ctx, updateProvider,
		arg.Name,
		arg.Protocol,
		arg.BaseUrl,
		arg.ApiKeyEnc,
		arg.IsDefault,
		arg.ID,
		arg.OrgID,
	)
	var i Provider
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Protocol,
		&i.BaseUrl,
		&i.ApiKeyEnc,
		&i.ModelsJson,
		&i.ModelsFetchedAt,
		&i.LastVerifiedAt,
		&i.IsDefault,
		&i.CreatedAt,
	)
	return i, err
}

const updateTaskFields = `-- name: UpdateTaskFields :one
UPDATE tasks
SET title = $3, body = $4, priority = $5
WHERE id = $1 AND org_id = $2
RETURNING id, org_id, board_id, title, body, status, priority, assignee_agent_id, created_by,
          idempotency_key, block_kind, consecutive_failures, workspace_kind, workspace_path,
          branch_name, completion_contract, goal_mode, goal_max_turns, current_run_id,
          cost_micros, tokens_in, tokens_out, created_at, started_at, completed_at, archived_at
`

type UpdateTaskFieldsParams struct {
	ID       string
	OrgID    string
	Title    string
	Body     string
	Priority int16
}

func (q *Queries) UpdateTaskFields(ctx context.Context, arg UpdateTaskFieldsParams) (Task, error) {
	row := q.db.QueryRow(ctx, updateTaskFields,
		arg.ID,
		arg.OrgID,
		arg.Title,
		arg.Body,
		arg.Priority,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.BoardID,
		&i.Title,
		&i.Body,
		&i.Status,
		&i.Priority,
		&i.AssigneeAgentID,
		&i.CreatedBy,
		&i.IdempotencyKey,
		&i.BlockKind,
		&i.ConsecutiveFailures,
		&i.WorkspaceKind,
		&i.WorkspacePath,
		&i.BranchName,
		&i.CompletionContract,
		&i.GoalMode,
		&i.GoalMaxTurns,
		&i.CurrentRunID,
		&i.CostMicros,
		&i.TokensIn,
		&i.TokensOut,
		&i.CreatedAt,
		&i.StartedAt,
		&i.CompletedAt,
		&i.ArchivedAt,
	)
	return i, err
}

const updateTaskStatus = `-- name: UpdateTaskStatus :one
UPDATE tasks
SET status = $4
WHERE id = $1 AND org_id = $2 AND status = $3
RETURNING id, org_id, board_id, title, body, status, priority, assignee_agent_id, created_by,
          idempotency_key, block_kind, consecutive_failures, workspace_kind, workspace_path,
          branch_name, completion_contract, goal_mode, goal_max_turns, current_run_id,
          cost_micros, tokens_in, tokens_out, created_at, started_at, completed_at, archived_at
`

type UpdateTaskStatusParams struct {
	ID       string
	OrgID    string
	Status   string
	Status_2 string
}

// The status transition guard is in the WHERE clause, not in Go: two writers
// racing on the same task produce one winner and one zero-row result, which the
// service maps to ErrConflict. That is what makes move/claim safe under load.
func (q *Queries) UpdateTaskStatus(ctx context.Context, arg UpdateTaskStatusParams) (Task, error) {
	row := q.db.QueryRow(ctx, updateTaskStatus,
		arg.ID,
		arg.OrgID,
		arg.Status,
		arg.Status_2,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.BoardID,
		&i.Title,
		&i.Body,
		&i.Status,
		&i.Priority,
		&i.AssigneeAgentID,
		&i.CreatedBy,
		&i.IdempotencyKey,
		&i.BlockKind,
		&i.ConsecutiveFailures,
		&i.WorkspaceKind,
		&i.WorkspacePath,
		&i.BranchName,
		&i.CompletionContract,
		&i.GoalMode,
		&i.GoalMaxTurns,
		&i.CurrentRunID,
		&i.CostMicros,
		&i.TokensIn,
		&i.TokensOut,
		&i.CreatedAt,
		&i.StartedAt,
		&i.CompletedAt,
		&i.ArchivedAt,
	)
	return i, err
}

const updateUserProfile = `-- name: UpdateUserProfile :one
UPDATE users
SET name       = $2,
    email      = $3,
    avatar_url = NULLIF($4::text, '')
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, email, name, password_hash, avatar_url, is_shadow, deleted_at, created_at
`

type UpdateUserProfileParams struct {
	ID        string
	Name      string
	Email     string
	AvatarURL string
}

type UpdateUserProfileRow struct {
	ID           string
	Email        string
	Name         string
	PasswordHash string
	AvatarURL    *string
	IsShadow     bool
	DeletedAt    pgtype.Timestamptz
	CreatedAt    pgtype.Timestamptz
}

// One statement, so a taken email (23505 on users_email_key) rolls the whole
// profile update back — no half-applied name change (US-AD89 AC2/AC3). The
// `deleted_at IS NULL` guard is what turns a closed account into zero rows.
//
// The cast on $4 is load-bearing: `NULLIF($4, ”)` alone gives sqlc no type to
// infer, so it falls back to a positional `Column4 interface{}` whose exact
// spelling drifts between sqlc releases and breaks the caller. `sqlc.arg` names
// the parameter and `::text` pins the type, so the generated field is stable.
func (q *Queries) UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (UpdateUserProfileRow, error) {
	row := q.db.QueryRow(ctx, updateUserProfile,
		arg.ID,
		arg.Name,
		arg.Email,
		arg.AvatarURL,
	)
	var i UpdateUserProfileRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.PasswordHash,
		&i.AvatarURL,
		&i.IsShadow,
		&i.DeletedAt,
		&i.CreatedAt,
	)
	return i, err
}
