// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"context"
)

type Querier interface {
	// Resolusi skills_json -> teks prompt (3.8: "resolusi slug -> skill saat menyusun
	// prompt agent"). Dikerjakan di SQL, bukan di Go, karena urutannya milik
	// array_positions: skills_json adalah pilihan yang BERURUTAN dan urutan itu
	// satu-satunya sinyal prioritas yang dipunyainya.
	AgentSkillBodies(ctx context.Context, arg AgentSkillBodiesParams) ([]AgentSkillBodiesRow, error)
	// US-AD73: archived agents keep their row (running tasks still resolve their
	// retry/limit source) but disappear from every assign dropdown.
	ArchiveAgent(ctx context.Context, arg ArchiveAgentParams) (ArchiveAgentRow, error)
	AssignTask(ctx context.Context, arg AssignTaskParams) (Task, error)
	// Setting `blocked` and its `block_kind` in one statement, because a blocked
	// task with no kind cannot be routed: the state machine (5.4) sends each kind
	// back to `ready` by a different action.
	BlockTask(ctx context.Context, arg BlockTaskParams) (Task, error)
	// 4c versi tabel agregat: cap, terpakai hari ini, dan status ambang N18.
	// COALESCE untuk board yang belum punya baris hari ini — cap tetap terbaca,
	// terpakai nol, jadi guardrail-nya tidak bergantung pada ada-tidaknya baris.
	BoardBudgetToday(ctx context.Context, arg BoardBudgetTodayParams) (BoardBudgetTodayRow, error)
	// US-AD32 cost gate reads this: spend for one board since local midnight.
	BoardSpendToday(ctx context.Context, arg BoardSpendTodayParams) (int64, error)
	// run_count naik sekali per run, bukan per step; dipanggil saat run berakhir.
	BumpDailyRunCount(ctx context.Context, boardID string) error
	// Fase 3d (5.2): kandidat yang parent-nya belum selesai tidak diklaim, tapi
	// dipindah ke 'blocked' dengan block_kind='dependency' supaya terlihat di papan
	// sebagai menunggu, bukan hilang dari pandangan. 4e.1 membangunkannya kembali.
	ClaimReadyTaskDepsBlocked(ctx context.Context, arg ClaimReadyTaskDepsBlockedParams) (int64, error)
	// Satu ULID per task, bukan satu untuk seluruh batch.
	//
	// Versi sebelumnya menulis `current_run_id = $4` untuk SEMUA baris yang diklaim,
	// jadi tiga task yang diklaim bersama akan berbagi satu run id. Dua akibatnya:
	// `StartRun` menolak task yang current_run_id-nya bukan run id yang dipanggil
	// (hanya satu yang lolos), dan baris `runs` yang lain tidak pernah ada padahal
	// task-nya sudah `running`. Sekarang pemanggil mengirim array ULID sepanjang
	// batch dan tiap baris mendapat indeksnya sendiri.
	//
	// `created_at ASC` mengikuti 4a: task lama didahulukan dalam prioritas yang sama
	// (versi lama memakai DESC, jadi FIFO-nya terbalik).
	//
	// Predikat dependency ikut di sini, bukan di Go: sebuah task yang parent-nya
	// belum `done`/`cancelled`/`archived` tidak boleh diklaim. Menaruhnya di SQL
	// berarti properti itu tidak bisa dilewati oleh pemanggil mana pun.
	// Dua CTE, bukan satu: Postgres menolak `FOR UPDATE` di query yang memakai window
	// function ("FOR UPDATE is not allowed with window functions"). Jadi lock dan
	// penomoran dipisah — CTE pertama mengunci batch-nya, CTE kedua menomori baris
	// yang sudah terkunci. Lock-nya tetap dipegang sampai transaksi commit, jadi
	// penomoran tidak membuka celah bagi dispatcher lain.
	ClaimReadyTasks(ctx context.Context, arg ClaimReadyTasksParams) ([]Task, error)
	ClaimShadowUser(ctx context.Context, arg ClaimShadowUserParams) error
	// Targeted claim for POST /tasks/{id}/claim (US-AD21). ClaimReadyTasks claims a
	// *batch* in priority order, which is the dispatcher's shape; a caller naming one
	// task needs that task or nothing. Same guard as the batch: the status and the
	// null run binding are preconditions in the WHERE clause, so two claimers racing
	// on one task produce one row and one zero-row conflict.
	ClaimTask(ctx context.Context, arg ClaimTaskParams) (Task, error)
	// Rotation and revocation are the same statement with a NULL ciphertext.
	ClearAgentProviderKey(ctx context.Context, arg ClearAgentProviderKeyParams) (ClearAgentProviderKeyRow, error)
	// providers_org_default_key is a non-deferrable partial unique index, so a
	// single `UPDATE ... SET is_default = (id = $x)` can still raise 23505: Postgres
	// checks the index per row, and the new default may be visited before the old
	// one is unset. Clearing first and setting second are two statements that
	// cannot collide. AC9 makes the cleared state legitimate, not a half-write.
	ClearDefaultProvider(ctx context.Context, orgID string) error
	// EndRun clears the binding. ClaimReadyTasks requires `current_run_id IS NULL`
	// (ARCHITECTURE 4b), so a finished run that left its id on the task would make
	// that task permanently unclaimable: J4's retry, J6's reclaim, and the
	// review -> ready path all end in `ready`, and none of them could ever be
	// claimed again.
	ClearTaskCurrentRun(ctx context.Context, arg ClearTaskCurrentRunParams) error
	ConsumePasswordReset(ctx context.Context, tokenHash string) (int64, error)
	// Guards US-AD20 AC4: an agent holding a task in `running` may not be deleted,
	// because the run it is executing would lose its retry/limit source mid-flight.
	CountAgentRunningTasks(ctx context.Context, arg CountAgentRunningTasksParams) (int64, error)
	// The assign picker hides archived agents (US-AD73 AC2). The count is what lets
	// the board say "N hidden" instead of silently omitting rows — the design's own
	// `✕ 1 agent diarsip disembunyikan` line.
	CountArchivedAgents(ctx context.Context, orgID string) (int64, error)
	CountBoardsInProject(ctx context.Context, arg CountBoardsInProjectParams) (int32, error)
	// Guards the last-owner rule: an org must never be left without an owner.
	CountOrgOwners(ctx context.Context, orgID string) (int32, error)
	// Decides whether a provider being created becomes the workspace default: the
	// first one does, so a workspace that has exactly one never has to pick.
	CountProviders(ctx context.Context, orgID string) (int32, error)
	// Counts unfinished parents: the dispatcher promotes a child to ready only when
	// this returns zero (ARCHITECTURE 4e).
	CountUnfinishedParents(ctx context.Context, childID string) (int32, error)
	// Agents. The agent is the retry/limit source for every run it executes.
	// Every mutable column UpdateAgent writes is written here too. The two drifted
	// once: `reasoning_effort` was bound only by UpdateAgent, so a client's value
	// was dropped in silence on create. internal/store/queries_columns_test.go is
	// the guard that keeps the two lists in step.
	//
	// provider_id is the registry reference (US-AD109). It is written here for the
	// same reason as everything else on this list: a create that omits it leaves
	// the agent pointing at no provider, which phase 5 reads as "no credential".
	CreateAgent(ctx context.Context, arg CreateAgentParams) (CreateAgentRow, error)
	// Agent skills (US-AD107). Skill is org-scoped data: users read and edit the
	// markdown, agents only read it. Nothing here exposes a write path an agent
	// could reach, and every query carries org_id explicitly.
	CreateAgentSkill(ctx context.Context, arg CreateAgentSkillParams) (AgentSkill, error)
	// Boards. columns_json is the board's view of status, never a new status.
	CreateBoard(ctx context.Context, arg CreateBoardParams) (Board, error)
	// Append-only event log. No UPDATE or DELETE is ever issued against events.
	CreateEvent(ctx context.Context, arg CreateEventParams) (Event, error)
	CreateLedgerEntry(ctx context.Context, arg CreateLedgerEntryParams) (LedgerEntry, error)
	CreateMembership(ctx context.Context, arg CreateMembershipParams) error
	CreateOrg(ctx context.Context, arg CreateOrgParams) (Org, error)
	CreateOrgKind(ctx context.Context, arg CreateOrgKindParams) error
	// M0 — password reset (US-AD88).
	//
	// The token is single-use and time-boxed, so the row is consumed by an UPDATE
	// that also stamps used_at: a SELECT-then-UPDATE pair would let two concurrent
	// redemptions both read an unconsumed row. Expiry and single-use are both in
	// the WHERE clause, so an expired or already-spent token matches zero rows and
	// the caller cannot tell the two apart (AC3).
	CreatePasswordReset(ctx context.Context, arg CreatePasswordResetParams) error
	// ============================================================================
	// M1 — projects, boards, agents, tasks, task_links, events
	//
	// Tenant scoping rule (ARCHITECTURE 17): every query below that touches an
	// org-scoped row carries org_id explicitly, even when the id alone would be
	// unique. There is no second code path that could forget the scope.
	// ============================================================================
	CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error)
	// Providers (US-AD109, DECISIONS 6A.J). The credential and the address live
	// here, once per workspace, instead of once per agent: agents point at a
	// provider row, so one edit reaches every agent that uses it (AC6). Every query
	// carries org_id explicitly, like the rest of this file.
	CreateProvider(ctx context.Context, arg CreateProviderParams) (Provider, error)
	// claim_lock dan claim_expires wajib diisi di sini, bukan opsional.
	// `claim_expires` adalah kolom yang membuat reclaim 4b mungkin: query itu
	// mensyaratkan `claim_expires IS NOT NULL`, jadi run yang dibiarkan NULL tidak
	// pernah bisa di-reclaim — agent yang hang akan memegang task `running` selamanya
	// dan jalur retry 10 tidak pernah kebagian. Batasnya max_runtime_seconds agent
	// (N9 4 jam): run yang melewatinya basi menurut definisi.
	// `$6::int` di kedua tempat, bukan `$6` polos: make_interval(secs) bertipe
	// double precision sementara kolomnya integer, dan Postgres menolak satu parameter
	// yang dipakai dengan dua tipe ("inconsistent types deduced for parameter").
	CreateRun(ctx context.Context, arg CreateRunParams) (CreateRunRow, error)
	// token_hash is SHA-256 of the 64-byte raw token; the raw token only ever
	// exists in the Set-Cookie (ARCHITECTURE 3.19).
	CreateSession(ctx context.Context, arg CreateSessionParams) error
	CreateStep(ctx context.Context, arg CreateStepParams) (Step, error)
	// Tasks. created_by is the acting user; assignee_agent_id is nullable.
	CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error)
	// Dependency DAG. Self-links are rejected by the table CHECK, and the service
	// rejects cycles before insert.
	CreateTaskLink(ctx context.Context, arg CreateTaskLinkParams) error
	CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error)
	DeleteAgent(ctx context.Context, arg DeleteAgentParams) error
	// System skills are not deletable: they are the baseline every workspace starts
	// from, and removing one would silently strip capability from existing agents.
	DeleteAgentSkill(ctx context.Context, arg DeleteAgentSkillParams) error
	DeleteBoard(ctx context.Context, arg DeleteBoardParams) error
	DeleteExpiredSessions(ctx context.Context) error
	DeleteMembership(ctx context.Context, arg DeleteMembershipParams) error
	DeleteModelPrice(ctx context.Context, arg DeleteModelPriceParams) (int64, error)
	DeleteProject(ctx context.Context, arg DeleteProjectParams) error
	DeleteProvider(ctx context.Context, arg DeleteProviderParams) error
	DeleteSessionByTokenHash(ctx context.Context, tokenHash string) error
	DeleteTask(ctx context.Context, arg DeleteTaskParams) error
	DeleteTaskLink(ctx context.Context, arg DeleteTaskLinkParams) error
	// Revokes every session of one user (US-AD88 AC2). Deliberately not scoped by
	// token: after a reset the operator has no trusted device, so all of them go.
	DeleteUserSessions(ctx context.Context, userID string) error
	// The cost rollup is computed from ledger_entries in the same statement that
	// closes the run, so runs.cost_micros can never disagree with the ledger it
	// summarises. A rollup maintained by the executor in a separate UPDATE would
	// drift the moment a run ends without one.
	EndRun(ctx context.Context, arg EndRunParams) (EndRunRow, error)
	FinishStep(ctx context.Context, arg FinishStepParams) (Step, error)
	GetAgent(ctx context.Context, arg GetAgentParams) (GetAgentRow, error)
	// The ONLY reader of the ciphertext column. Returns it alone so the sealed bytes
	// never travel inside a struct that gets logged, cached, or serialised.
	GetAgentProviderKey(ctx context.Context, arg GetAgentProviderKeyParams) ([]byte, error)
	GetAgentSkill(ctx context.Context, arg GetAgentSkillParams) (AgentSkill, error)
	GetBoard(ctx context.Context, arg GetBoardParams) (Board, error)
	// The single membership row that answers "is this user in this org, and as
	// what". Every org-scoped handler resolves its tenant through this query, so
	// there is no second code path that could forget the org_id scope.
	GetMembership(ctx context.Context, arg GetMembershipParams) (Membership, error)
	GetModelPrice(ctx context.Context, arg GetModelPriceParams) (AgentModelPrice, error)
	GetOrgByID(ctx context.Context, id string) (Org, error)
	GetPasswordReset(ctx context.Context, tokenHash string) (PasswordReset, error)
	// The registration-kind org where THIS user is the owner: that is the only
	// shape that means "my personal workspace". Membership alone is not enough —
	// an invitee is a member of someone else's registration-kind org, and
	// resolving it here would hand them a workspace that is not theirs.
	GetPersonalWorkspace(ctx context.Context, userID string) (Org, error)
	GetProject(ctx context.Context, arg GetProjectParams) (Project, error)
	// Returns api_key_enc because the handler layer is what decrypts, and it needs
	// the sealed bytes to do so. Nothing in this file puts them in a response.
	GetProvider(ctx context.Context, arg GetProviderParams) (Provider, error)
	// The one query that hands out ciphertext, for the one path that decrypts it
	// before probing an upstream (phase 3). Returning it as a scalar rather than as
	// a column of GetProvider is deliberate: the domain Provider carries no
	// ciphertext, so no read path can leak what it never receives.
	// api_key_enc is nullable (a local endpoint that checks nothing), and a NULL
	// scans into a nil []byte rather than an error.
	GetProviderKey(ctx context.Context, arg GetProviderKeyParams) ([]byte, error)
	GetRun(ctx context.Context, arg GetRunParams) (GetRunRow, error)
	// Sliding idle window (US-AD02 AC4): a session that has been idle longer than
	// the idle timeout is rejected, so last_seen_at is bumped on every use.
	GetSessionByTokenHash(ctx context.Context, arg GetSessionByTokenHashParams) (GetSessionByTokenHashRow, error)
	GetTask(ctx context.Context, arg GetTaskParams) (Task, error)
	GetUserByEmail(ctx context.Context, lower string) (GetUserByEmailRow, error)
	GetUserByID(ctx context.Context, id string) (GetUserByIDRow, error)
	// ============================================================================
	// M4 irisan 2: dispatcher tick (heartbeat, reclaim, dependency, budget, klaim)
	// ============================================================================
	// Fase 1 tick. 5.1: "perbarui last_heartbeat_at untuk semua run yang sedang
	// dirunning oleh instance ini" — kuncinya claim_lock (identitas instance), bukan
	// board: `runs` memang tidak punya board_id, dan dua instance di board yang sama
	// tidak boleh saling memperpanjang hidup.
	HeartbeatOwnedRuns(ctx context.Context, arg HeartbeatOwnedRunsParams) error
	HeartbeatRun(ctx context.Context, arg HeartbeatRunParams) (HeartbeatRunRow, error)
	// The only writer of tasks.consecutive_failures. The retry ceiling (J4) is read
	// from this column, so without an increment a failing task retries forever:
	// the ceiling would be compared against a number that never moves.
	IncrementTaskFailures(ctx context.Context, arg IncrementTaskFailuresParams) (int16, error)
	// The list needs "dipakai N agent" on every row, so usage is resolved in the
	// same round trip: a per-row query would be N+1 against a table the user scrolls.
	// `?` is jsonb containment for a top-level array element, i.e. the slug is in
	// agents.skills_json. Archived agents are excluded: they no longer receive work,
	// so they must not make a skill look live.
	ListAgentSkillsWithUsage(ctx context.Context, orgID string) ([]ListAgentSkillsWithUsageRow, error)
	// Returns archived rows too, deliberately. The registry is where a user finds an
	// agent again to unarchive it, so filtering them out here would make archiving
	// irreversible from the UI. Callers that must not offer a retired agent (the
	// assign dropdown, US-AD73 AC2) filter on `archived_at` themselves — see
	// ListAgentsUsingSkill and the task-assign path.
	ListAgents(ctx context.Context, arg ListAgentsParams) ([]ListAgentsRow, error)
	// AC5: the 409 has to name the agents pinning this provider, so this is a read
	// of names the caller can already list, not a count.
	ListAgentsUsingProvider(ctx context.Context, arg ListAgentsUsingProviderParams) ([]ListAgentsUsingProviderRow, error)
	// Feeds the "dipakai oleh" list under the editor; each name routes to the agent
	// detail page, which is what stops a user from editing a live skill blindly.
	ListAgentsUsingSkill(ctx context.Context, arg ListAgentsUsingSkillParams) ([]ListAgentsUsingSkillRow, error)
	// US-AD73 AC2: the assign dropdown must never offer a retired agent. This is the
	// deliberate counterpart to ListAgents, which returns archived rows so the
	// registry can unarchive them.
	ListAssignableAgents(ctx context.Context, orgID string) ([]ListAssignableAgentsRow, error)
	// The real assign picker for a board: every active agent of the board's own
	// project, ordered the way the picker shows them. It is the source of the
	// preview's "Filter Active Only" claim, so the section proves AC2 against the
	// same rows the task-create modal would offer.
	// `has_provider_key` here is the PROVIDER's key, not the agent's column. DECISIONS
	// 6A.J moved credentials to `providers` ("sekali per ruang kerja, dirujuk banyak
	// agent") and US-AD109 AC6 says the agent keeps no copy, so reading
	// `a.has_provider_key` would mark an agent unready while its provider holds a
	// working key. An agent with no provider row keeps its own column as the answer:
	// nothing else can hold a credential for it. This is the same rule the registry
	// and the agent detail apply (frontend `agentState`).
	ListAssignableAgentsForBoard(ctx context.Context, arg ListAssignableAgentsForBoardParams) ([]ListAssignableAgentsForBoardRow, error)
	// Dispatcher claim (ARCHITECTURE 4b): one atomic statement. SKIP LOCKED lets
	// concurrent dispatchers claim disjoint batches instead of serialising on the
	// board row, and the status='ready' predicate means a second claimer sees an
	// empty set rather than a duplicate claim.
	// Screen 28-agent-detail draws the "simulasi penugasan" section: which tasks this
	// agent holds, and the guarantee that archiving it does not cut a running one
	// off (US-AD73 AC1). Archived tasks are excluded (they are gone from the board,
	// like ListBoardTasks), and the order puts live work first so the running row is
	// the one an operator sees without scrolling.
	ListAssignedTasks(ctx context.Context, arg ListAssignedTasksParams) ([]ListAssignedTasksRow, error)
	// SSE resume: events newer than the client's Last-Event-ID for one board.
	ListBoardEventsAfter(ctx context.Context, arg ListBoardEventsAfterParams) ([]Event, error)
	ListBoardLedger(ctx context.Context, arg ListBoardLedgerParams) ([]LedgerEntry, error)
	// Filters are optional and nullable: NULL means "no constraint", which is why
	// each is written as `sqlc.narg(...) IS NULL OR ...` rather than assembled in
	// Go. The contract (§6.2.16) advertises `status, assignee, search`; a filter
	// that only exists in the client is a filter that silently diverges from the
	// one the API documents.
	//
	// `sqlc.narg` rather than a sentinel: an empty string is a legitimate search
	// term for "no match", so it cannot double as "unset".
	ListBoardTasks(ctx context.Context, arg ListBoardTasksParams) ([]Task, error)
	ListBoards(ctx context.Context, arg ListBoardsParams) ([]Board, error)
	// 5.1: "satu instance per board yang aktif". Daftar board yang punya project
	// (board tanpa project tidak bisa punya task). Instance memilihnya sendiri lewat
	// tick: tidak ada registry pusat, jadi menambah instance tidak butuh koordinasi.
	// Dibatasi ke board yang punya setidaknya satu task `ready` supaya org dengan
	// puluhan board tidak membayar satu query budget per board tiap 2 detik.
	ListClaimableBoards(ctx context.Context) ([]ListClaimableBoardsRow, error)
	ListMembers(ctx context.Context, orgID string) ([]ListMembersRow, error)
	ListModelPrices(ctx context.Context, orgID string) ([]AgentModelPrice, error)
	// The org roster a user belongs to, with their role in each. Scoping is
	// by membership, not by the caller's guess of an org id, so this cannot
	// leak a tenant the user is not part of (tenant isolation, ARCHITECTURE 17).
	ListOrgsForUser(ctx context.Context, userID string) ([]ListOrgsForUserRow, error)
	ListProjects(ctx context.Context, orgID string) ([]Project, error)
	// The default sorts first because it is what the agent form preselects (AC9).
	ListProviders(ctx context.Context, orgID string) ([]Provider, error)
	ListRunLedger(ctx context.Context, arg ListRunLedgerParams) ([]LedgerEntry, error)
	ListRunSteps(ctx context.Context, arg ListRunStepsParams) ([]Step, error)
	// AC7's automatic half. This is the ONE provider query deliberately not scoped by
	// org_id: the background refresher has no tenant in hand — it walks every
	// workspace — so a `WHERE org_id = $1` here would make it impossible to write.
	// Request-serving code must never call this; the reads that answer a user are
	// List/Get, and both carry org_id.
	//
	// NULL models_fetched_at is stale, not fresh: "never fetched" is exactly the
	// state that needs a fetch. The ORDER BY puts those first so a workspace that
	// just registered a provider is served before one that merely aged out.
	//
	// The id tiebreaker makes the batch deterministic. Without it the order among
	// equally-stale rows is unspecified, so with more stale providers than the batch
	// cap the same subset can be chosen every pass and the rest starve.
	// ponytail: deterministic is not the same as fair — a permanently broken provider
	// stays stale forever and keeps its slot. Serving every workspace round-robin
	// needs a last_attempt_at column; add it if a provider is ever observed never
	// getting its turn.
	ListStaleProviderModels(ctx context.Context, arg ListStaleProviderModelsParams) ([]Provider, error)
	ListTaskChildren(ctx context.Context, parentID string) ([]ListTaskChildrenRow, error)
	ListTaskEvents(ctx context.Context, taskID *string) ([]Event, error)
	ListTaskParents(ctx context.Context, childID string) ([]ListTaskParentsRow, error)
	ListTaskRuns(ctx context.Context, arg ListTaskRunsParams) ([]ListTaskRunsRow, error)
	NextRunAttempt(ctx context.Context, taskID string) (int32, error)
	// 4b: run 'running' tanpa heartbeat 15 menit (N8) di-reclaim dalam satu
	// transaksi: run ditutup dengan outcome 'reclaimed', task dikembalikan ke
	// 'ready' dengan consecutive_failures naik (§10.3). Task yang sudah melewati
	// plafon percobaan ditandai 'failed' alih-alih 'ready', supaya tidak diklaim
	// ulang tanpa batas.
	ReclaimStaleRuns(ctx context.Context, arg ReclaimStaleRunsParams) ([]ReclaimStaleRunsRow, error)
	// Rollup kolom biaya/token di runs sendiri, bukan hanya di ledger: 5.3 memakai
	// `runs.cost_micros` untuk laporan per run, dan agent tidak pernah menulisnya.
	RecordRunUsage(ctx context.Context, arg RecordRunUsageParams) error
	// Lepaskan task yang sudah diklaim tapi tidak bisa dijalankan (tidak ada agent,
	// agent diarsipkan, atau tidak ada alamat provider) — termasuk kasus StartRun
	// gagal, di mana baris `runs` TIDAK ADA sehingga EndRun 4b tidak bisa dipakai.
	//
	// Kenapa ini harus ada: klaim menulis `status='running'` + current_run_id. Kalau
	// persiapan gagal dan tidak ada yang melepasnya, task itu `running` selamanya —
	// tidak terlihat reclaim (tidak ada run untuk di-reclaim) dan tidak terlihat
	// predikat klaim (bukan `ready`). Satu task, satu user, hilang dari antrean.
	//
	// Diterapkan di sini, bukan di Go, karena 10.2 memetakan `needs_input` ke
	// `blocked` dan sisanya ke `failed`; memisahkannya membuat papan bisa menampilkan
	// "menunggu manusia" alih-alih kehilangan tasknya.
	ReleaseClaim(ctx context.Context, arg ReleaseClaimParams) (ReleaseClaimRow, error)
	// Keep the rename and its audit row in one statement: if the INSERT fails, the
	// data-modifying CTE is rolled back too (US-AD77 fail-closed).
	RenameOrgWithAudit(ctx context.Context, arg RenameOrgWithAuditParams) error
	ResetTaskFailures(ctx context.Context, arg ResetTaskFailuresParams) error
	// US-AD86: store the sealed credential. Encryption/decryption lives in
	// internal/crypto; this statement only ever sees ciphertext, so a DB dump alone
	// cannot recover a provider key. Returning the derived flag lets the handler
	// answer without a second round-trip.
	SetAgentProviderKey(ctx context.Context, arg SetAgentProviderKeyParams) (SetAgentProviderKeyRow, error)
	// AC7: the fetched list and the moment it was fetched, written together so a
	// freshness check can never see one without the other.
	SetProviderModels(ctx context.Context, arg SetProviderModelsParams) error
	// AC3: stamped only after the inference probe passes. Nothing else writes this
	// column, so a non-null value always means a probe succeeded.
	SetProviderVerifiedAt(ctx context.Context, arg SetProviderVerifiedAtParams) error
	// Claiming sets tasks.current_run_id (there is no UPDATE for it anywhere else),
	// so this is what StartRun uses to bind a run to its task.
	SetTaskCurrentRun(ctx context.Context, arg SetTaskCurrentRunParams) (Task, error)
	TouchSession(ctx context.Context, tokenHash string) error
	UnarchiveAgent(ctx context.Context, arg UnarchiveAgentParams) (UnarchiveAgentRow, error)
	// US-AD96: the edit form replaces every mutable field at once, so this is a
	// full update rather than a partial patch.
	//
	// provider_id is the registry reference (US-AD109). It is nullable and stays
	// that way: an agent with no provider of its own uses the workspace default.
	UpdateAgent(ctx context.Context, arg UpdateAgentParams) (UpdateAgentRow, error)
	// AC6: version rises on every edit and older content is never rewritten in
	// place, so a run that already loaded v3 keeps meaning what it meant.
	UpdateAgentSkill(ctx context.Context, arg UpdateAgentSkillParams) (AgentSkill, error)
	UpdateBoardBudget(ctx context.Context, arg UpdateBoardBudgetParams) error
	UpdateBoardColumns(ctx context.Context, arg UpdateBoardColumnsParams) error
	UpdateBoardName(ctx context.Context, arg UpdateBoardNameParams) error
	UpdateMembershipRole(ctx context.Context, arg UpdateMembershipRoleParams) error
	UpdateOrgName(ctx context.Context, arg UpdateOrgNameParams) error
	UpdateProjectName(ctx context.Context, arg UpdateProjectNameParams) error
	// A partial update, deliberately — not the full-replace shape UpdateAgent uses.
	// A full replace would blank every column the caller omitted, and three of them
	// (models_json, models_fetched_at, last_verified_at) belong to phase 3: renaming
	// a provider would silently erase its model list and its verification
	// timestamp. COALESCE keeps whatever the request leaves out, and those three
	// columns are not in the SET list at all.
	//
	// There is no way to clear api_key_enc here: passing NULL means "leave it", so
	// a provider that has a credential keeps it. Removing a credential is not in
	// the contract's seven endpoints.
	UpdateProvider(ctx context.Context, arg UpdateProviderParams) (Provider, error)
	UpdateTaskFields(ctx context.Context, arg UpdateTaskFieldsParams) (Task, error)
	// The status transition guard is in the WHERE clause, not in Go: two writers
	// racing on the same task produce one winner and one zero-row result, which the
	// service maps to ErrConflict. That is what makes move/claim safe under load.
	UpdateTaskStatus(ctx context.Context, arg UpdateTaskStatusParams) (Task, error)
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error
	// One statement, so a taken email (23505 on users_email_key) rolls the whole
	// profile update back — no half-applied name change (US-AD89 AC2/AC3). The
	// `deleted_at IS NULL` guard is what turns a closed account into zero rows.
	//
	// The cast on $4 is load-bearing: `NULLIF($4, '')` alone gives sqlc no type to
	// infer, so it falls back to a positional `Column4 interface{}` whose exact
	// spelling drifts between sqlc releases and breaks the caller. `sqlc.arg` names
	// the parameter and `::text` pins the type, so the generated field is stable.
	UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (UpdateUserProfileRow, error)
	// 4c/5.3: agregat biaya harian per board. Di-UPSERT setiap step selesai, jadi
	// dispatcher tidak perlu menjumlahkan ledger_entries tiap tick.
	UpsertDailyBoardCost(ctx context.Context, arg UpsertDailyBoardCostParams) error
	// ---------------------------------------------------------------- harga manual --
	// Tingkat 1 resolusi harga (DECISIONS 6A.C). Baris di sini MENANG atas tabel
	// katalog exact maupun pattern: itu yang membuat `price_source` bernilai
	// 'manual' di ledger. Nama model disimpan apa adanya, sama seperti yang
	// dicocokkan `pricing.Resolve`.
	UpsertModelPrice(ctx context.Context, arg UpsertModelPriceParams) (AgentModelPrice, error)
	// 4e.1: setelah sebuah task masuk 'done', anak yang diblokir karena dependency
	// dibangunkan. Hanya yang block_kind='dependency' — blokir karena policy atau
	// kebutuhan input manusia bukan urusan query ini.
	WakeDependents(ctx context.Context, parentID string) error
}

var _ Querier = (*Queries)(nil)
