#!/usr/bin/env python3
"""Regenerate docs/CHECKLIST.md from docs/COVERAGE.md plus a status sidecar.

Why a sidecar: COVERAGE.md is generated by `screens.py` and CHECKLIST.md is
derived from it, so neither is the right place to record progress — both get
overwritten. `tools/checklist_status.json` is the only hand-edited file, and it
holds story -> status. Regenerating is then always safe.

Usage:
    python tools/update_checklist.py                    # regenerate from sidecar
    python tools/update_checklist.py US-AD04 pass       # set one story, then regenerate
    python tools/update_checklist.py US-AD04            # show one story
"""
import json
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
COVERAGE = ROOT / "docs" / "COVERAGE.md"
SIDECAR = ROOT / "tools" / "checklist_status.json"
OUT = ROOT / "docs" / "CHECKLIST.md"

MILESTONES = ["M0", "M1", "M2", "M3", "M4"]
STATUSES = {"pass": "✅ PASS", "wip": "🔨 dikerjakan", "todo": "⬜", "defer": "⏸️ ditunda", "fail": "❌ gagal"}


def parse_coverage():
    text = COVERAGE.read_text(encoding="utf-8")
    rows = re.findall(r"^\| `(US-AD\d+)` \| (\w+) \| (M\d) \| (.+?) \| (.+?) \|$", text, re.M)
    if not rows:
        sys.exit("no stories parsed from COVERAGE.md — did its table format change?")
    return rows


def load_sidecar():
    if SIDECAR.exists():
        return json.loads(SIDECAR.read_text(encoding="utf-8"))
    return {}


def render(rows, status):
    by = {}
    for sid, pri, ms, title, scr in rows:
        by.setdefault(ms, []).append((sid, pri, title, scr))

    unknown = set(status) - {r[0] for r in rows}
    if unknown:
        sys.exit(f"sidecar names stories that are not in COVERAGE.md: {sorted(unknown)}")

    out = [
        "# CHECKLIST — AgentDeck M0 → M4",
        "",
        "> Dihasilkan oleh `tools/update_checklist.py` dari `docs/COVERAGE.md` + `tools/checklist_status.json`.",
        "> **Jangan edit file ini** — edit sidecar-nya, lalu jalankan ulang tool-nya.",
        "> Status: ✅ PASS · 🔨 dikerjakan · ⬜ belum · ⏸️ ditunda (keputusan user) · ❌ gagal",
        "",
        "| Story | Pri | MS | Judul | Layar | Status |",
        "|---|---|---|---|---|---|",
    ]
    for ms in MILESTONES:
        for sid, pri, title, scr in sorted(by[ms]):
            out.append(f"| `{sid}` | {pri} | {ms} | {title} | {scr} | {STATUSES[status.get(sid, 'todo')]} |")

    total = sum(len(by[m]) for m in MILESTONES)
    passed = sum(1 for m in MILESTONES for r in by[m] if status.get(r[0]) == "pass")
    deferred = sum(1 for m in MILESTONES for r in by[m] if status.get(r[0]) == "defer")
    out += ["", f"**Total M0–M4: {total} story** ({passed} PASS, {deferred} ditunda)", ""]
    out += ["## Progres per milestone", "", "| Milestone | Story | PASS | Sisa |", "|---|---|---|---|"]
    for ms in MILESTONES:
        n = len(by[ms])
        p = sum(1 for r in by[ms] if status.get(r[0]) == "pass")
        out.append(f"| {ms} | {n} | {p} | {n - p} |")
    out.append("")
    out += render_notes(status)
    return "\n".join(out)


# Notes for stories whose status needs a caveat that the one-line table cannot
# carry — a story that is half done, or one deliberately deferred. They live
# here rather than in CHECKLIST.md because that file is regenerated from this
# script on every run: a note typed into the output would be silently erased by
# the next `update_checklist.py` call. Keyed by story id; rendered only when the
# story is actually in that state.
NOTES = {
    "US-AD73": (
        "wip",
        "backend PASS, UI sebagian",
        [
            "Sudah jalan: `PATCH /api/v1/agents/{id}` dengan `{\"archived\": true|false}`; "
            "guard 409 saat agent masih memegang run; guard 403 untuk member/viewer; "
            "`archived_at` dikembalikan di `GET`/list/`POST`; badge `DIARSIP` dan filter "
            "`DIARSIP` di registry; agent terarsip dikeluarkan dari hitungan siap-ditugaskan.",
            "AC2 sudah punya sumber data: `GET /api/v1/boards/{board_id}/assignable-agents` "
            "memanggil `ListAssignableAgentsForBoard` (`cmd/api/boards.go`, `internal/board/pgx.go`), "
            "dan predikatnya mengecualikan agent terarsip. Catatan lama yang bilang "
            "\"tidak ada handler maupun endpoint yang memakainya\" sudah tidak benar dan "
            "dikoreksi di sini.",
            "AC1 (task `running` tetap tuntas saat agent diarsip) baru bisa dibuktikan "
            "end-to-end setelah executor M4 ada.",
            "Status PASS ditahan sampai kedua AC itu bisa dibuktikan — bukan karena "
            "gate merah.",
        ],
    ),
    "US-AD67": (
        "todo",
        "endpoint validate ada, cek harga belum",
        [
            "Sudah jalan: `POST /api/v1/agents/{id}/validate` (Member) ada dan "
            "terverifikasi runtime; `PATCH /api/v1/agents/{id}` menerima "
            "`provider`/`model` dengan floor role di route.",
            "Belum: AC1 dan AC2 menuntut kombinasi `provider`+`model` yang tidak ada di "
            "tabel harga ditolak **400**. `validateAgent` di `internal/board/service.go` "
            "hanya memeriksa format nama, retry policy, rentang runtime, dan pasangan "
            "`base_url`. Nol panggilan ke `internal/pricing` dari jalur create/update.",
            "Halaman detail (`28-agent-detail`) sudah menampilkan tarif dari "
            "`GET /agent-catalog`, tetapi itu lapisan tampilan — bukan penegakan AC.",
        ],
    ),
    "US-AD108": (
        "todo",
        "label estimasi di UI selesai, penulis ledger baru ada",
        [
            "Sudah jalan: AC1 — setiap angka biaya di UI melewati "
            "`formatEstimatedMicroUSD`, yang menuliskan `(estimate)`. "
            "`GET /agent-catalog` mengirim `estimate: true` dan `disclaimer` dari server, "
            "jadi klien tidak bisa diam-diam menghapus labelnya.",
            "AC2/AC3 sebagian: `ledger_entries` **sudah punya penulis** sejak M4 — "
            "`internal/board/runtime.go` + query `RecordLedgerEntry` menulis "
            "`price_source`, `price_version`, dan `pricing_model` per baris, dan itu "
            "dibuktikan lawan API nyata (`tools/probe-m5.py`: satu entri, "
            "`source=catalog`). Catatan lama yang bilang \"nol query sqlc dan nol handler\" "
            "sudah tidak benar. Yang masih perlu dibuktikan sebelum statusnya naik: "
            "jalur `manual` (harga tier-1 menimpa katalog) dan `pattern` ikut tercatat "
            "di baris ledger, bukan cuma di resolusi harga.",
            "AC5 (5 komponen, `reasoning` tidak pernah disamakan dengan `output`) sudah "
            "terpenuhi di tabel harga: 271 entri membawa `ReasoningMicrosPer1M` terpisah "
            "dan gate `verify_suite.py` memeriksa blok rumusnya.",
        ],
    ),
}


def render_notes(status):
    """Per-story caveats, emitted only for stories currently in the noted state."""
    blocks = []
    for sid, (want, headline, bullets) in NOTES.items():
        if status.get(sid) != want:
            continue
        blocks += [f"### Catatan status — `{sid}` ({STATUSES[want]})", "", f"**{headline}.**", ""]
        blocks += [f"- {b}" for b in bullets]
        blocks.append("")
    return blocks


def main(argv):
    rows = parse_coverage()
    status = load_sidecar()

    if len(argv) >= 2:
        sid = argv[1]
        if len(argv) == 2:
            print(f"{sid}: {status.get(sid, 'todo')}")
            return 0
        word = argv[2].lower()
        if word not in STATUSES:
            sys.exit(f"unknown status {word!r}; pick one of {sorted(STATUSES)}")
        if sid not in {r[0] for r in rows}:
            sys.exit(f"{sid} is not a story in COVERAGE.md")
        status[sid] = word
        SIDECAR.parent.mkdir(parents=True, exist_ok=True)
        SIDECAR.write_text(json.dumps(status, indent=1, sort_keys=True) + "\n", encoding="utf-8")
        print(f"{sid} -> {word}")

    OUT.write_text(render(rows, status) + "\n", encoding="utf-8")
    passed = sum(1 for v in status.values() if v == "pass")
    print(f"wrote {OUT.relative_to(ROOT)} ({passed} PASS, {len(status)} tracked)")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
